// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AdminRequestDecision = {
    decisionKey?: string | null;
    evidenceUrl?: string | null;
    expiresAt?: string | null;
    rationale?: string | null;
};

export type AdminRequestHistoryEvent = {
    actor: string;
    at: string;
    reason?: string | null;
    state: AdminRequestState;
};

export type AdminRequestKind = 'ceiling_exceeded' | 'cumulative_exhausted' | 'within_ceiling';

export type AdminRequestRequester = {
    displayEmail: string;
    userId: string;
};

export type AdminRequestResponse = {
    apiVersion: string;
    request: AdminRequestView;
};

export type AdminRequestSource = 'envelope_request' | 'runtime_exception' | 'escalation';

export type AdminRequestState = 'requested' | 'escalated' | 'auto_approved' | 'approved' | 'rejected' | 'expired';

export type AdminRequestTemplate = {
    displayName: string;
    id: string;
    revision: number;
};

export type AdminRequestView = {
    createdAt: string;
    decision?: null | AdminRequestDecision;
    deltas: Array<DirectAdmissionDelta>;
    escalation?: null | EscalationView;
    history: Array<AdminRequestHistoryEvent>;
    id: string;
    kind: AdminRequestKind;
    requestedEnvelope?: null | BrowserEnvelope;
    requester: AdminRequestRequester;
    source: AdminRequestSource;
    state: AdminRequestState;
    stateActor: string;
    stateAt: string;
    template: AdminRequestTemplate;
    templateEnvelope?: null | BrowserEnvelope;
};

export type AdminRequestsResponse = {
    apiVersion: string;
    nextCursor?: string | null;
    requests: Array<AdminRequestView>;
};

export type AdminRequestsSummaryResponse = {
    apiVersion: string;
    escalated: number;
    needsAction: number;
    requested: number;
};

export type AgentRunAvailability = 'available' | 'partial' | 'unavailable';

export type AgentRunDataStatus = {
    availability: AgentRunAvailability;
    observedAt?: string | null;
    reason?: string | null;
    source: string;
};

export type AgentRunResponse = {
    apiVersion: string;
    run: AgentRunView;
};

export type AgentRunSpendView = {
    currency: string;
    exhausted: boolean;
    observedAmount: string;
};

export type AgentRunTimelineEventView = {
    at: string;
    kind: 'phase';
    phase: TaskPhase;
    provenance: AgentRunTimelineProvenanceView;
} | {
    at: string;
    kind: 'finalizationRequested';
    provenance: AgentRunTimelineProvenanceView;
} | {
    at: string;
    kind: 'finalized';
    provenance: AgentRunTimelineProvenanceView;
} | {
    at: string;
    details: unknown;
    kind: 'stage';
    provenance: AgentRunTimelineProvenanceView;
    stage: string;
};

export type AgentRunTimelineProvenanceView = 'recorded' | 'backfilled';

export type AgentRunTimelineResponse = {
    apiVersion: string;
    events: Array<AgentRunTimelineEventView>;
    history: AgentRunDataStatus;
    taskUid: string;
};

export type AgentRunView = {
    actingUser?: string | null;
    allocatedBudget: Budget;
    authority: AgentRunDataStatus;
    codingAgentRuntime: string;
    configuredModels: Array<ModelRef>;
    createdAt: string;
    envelopeRevision?: number | null;
    errorCategory?: string | null;
    finalizationRequested: boolean;
    finalized: boolean;
    githubRun: AgentRunDataStatus;
    grantedTools: Array<ToolGrant>;
    inferenceActivity: AgentRunDataStatus;
    lifecycle: AgentRunDataStatus;
    observedSpend?: null | AgentRunSpendView;
    owner: string;
    phase: TaskPhase;
    resources: AgentRunDataStatus;
    runtimeOwnership: RuntimeOwnership;
    runtimeUid?: string | null;
    spend: AgentRunDataStatus;
    submitterService: string;
    taskUid: string;
    toolActivity: AgentRunDataStatus;
    updatedAt: string;
    workflow: string;
};

export type AgentRunsResponse = {
    apiVersion: string;
    nextCursor?: string | null;
    runs: Array<AgentRunView>;
};

export type AgentRuntimeSpec = {
    agentType: AgentType;
    bindings?: Array<BindingRef> | null;
    budget: Budget;
    canonicalAuthority?: null | CanonicalAuthorityBinding;
    llms: Array<ModelRef>;
    owner: Email;
    principal: Principal;
    runner?: RunnerRequirements;
    tools: Array<ToolGrant>;
    ttl: Duration;
};

export type AgentType = {
    name: string;
};

export type AllRunsResponse = {
    apiVersion: string;
    facets: BrowserRunFacets;
    nextCursor?: string | null;
    runs: Array<AllRunsView>;
};

export type AllRunsView = BrowserRunView & {
    ownerDisplayEmail?: string | null;
    /**
     * Opaque canonical identifier only; display email and acting-user identities stay server-side.
     */
    ownerUserId?: string | null;
};

export type ApprovalRequest = {
    evidenceUrl: string;
    expiresAt: string;
    rationale: string;
};

export type ApproveEnvelopeRequestBody = {
    evidenceUrl?: string | null;
    expiresAt?: string | null;
    /**
     * Omitted only by legacy clients that approve without decision metadata.
     */
    rationale?: string | null;
};

export type AuthorEnvelopeTemplateBody = {
    autoProvisionThreshold?: null | BrowserEnvelope;
    displayName: string;
    envelope: BrowserEnvelope;
    memberRoles: Array<string>;
};

export type AuthorityRequirements = {
    budget: BudgetRequirement;
    llms: Array<ModelRequirement>;
    runner: RunnerRequirement;
    tools: Array<ToolRequirement>;
    ttl: Duration;
};

export type AvailableEnvelopeTemplate = {
    autoProvisionThreshold?: null | BrowserEnvelope;
    ceiling: BrowserEnvelope;
    displayName: string;
    id: string;
    revision: number;
};

export type AvailableProviderConnection = {
    displayName: string;
    enabled: boolean;
    provider: string;
};

export type BindingRef = string;

export type BoundedRef = string;

export type BoundedText = string;

export type BrowserApprovalView = {
    actor: string;
    approvalId: string;
    counterexample: string;
    decisionKey?: string | null;
    envelopeRevision: number;
    evidenceUrl?: string | null;
    memberRole: string;
    proposedSpec: AgentRuntimeSpec;
    runtimeUid: string;
};

export type BrowserApprovalsResponse = {
    apiVersion: string;
    approvals: Array<BrowserApprovalView>;
    envelopeRequests: Array<BrowserEnvelopeRequestView>;
};

export type BrowserDecisionReferenceResponse = {
    apiVersion: string;
    approvalId: string;
    decisionKey: string;
    evidenceUrl: string;
};

export type BrowserEnvelope = {
    revision: number;
    spec: BrowserEnvelopeSpec;
};

export type BrowserEnvelopeRequestDecisionReferenceResponse = {
    apiVersion: string;
    decisionKey: string;
    evidenceUrl: string;
    requestId: string;
};

export type BrowserEnvelopeRequestDecisionResponse = {
    apiVersion: string;
    request: BrowserEnvelopeRequestDecisionView;
};

export type BrowserEnvelopeRequestDecisionView = {
    actedBy: string;
    approvalId?: string | null;
    approvedEnvelope?: null | BrowserEnvelope;
    decisionKey?: string | null;
    envelopeDigest?: string | null;
    envelopeInstanceId?: string | null;
    evidenceUrl?: string | null;
    expiresAt?: string | null;
    rationale?: string | null;
    reason?: string | null;
    requestId: string;
    requestedEnvelope: BrowserEnvelope;
    status: string;
    statusAt: string;
    templateId: string;
    templateRevision: number;
};

export type BrowserEnvelopeRequestView = {
    createdAt: string;
    ownerDisplayEmail: string;
    requestId: string;
    requestedEnvelope: BrowserEnvelope;
    templateEnvelope: BrowserEnvelope;
    templateId: string;
    templateRevision: number;
};

export type BrowserEnvelopeSpec = {
    budget: Budget;
    llms: Array<ModelRef>;
    runner?: RunnerRequirements;
    runtimeMinutesLimit?: string | null;
    tools: Array<ToolGrant>;
    ttl: Duration;
};

export type BrowserEnvelopeTemplateListItem = {
    autoProvisionThreshold?: null | BrowserEnvelope;
    displayName: string;
    envelope: BrowserEnvelope;
    id: string;
    /**
     * Compatibility alias for clients written before templates could target multiple roles.
     */
    memberRole: string;
    memberRoles: Array<string>;
};

export type BrowserEnvelopeTemplateListResponse = {
    apiVersion: string;
    templates: Array<BrowserEnvelopeTemplateListItem>;
};

export type BrowserEnvelopeTemplateResponse = {
    apiVersion: string;
    autoProvisionThreshold?: null | BrowserEnvelope;
    displayName: string;
    envelope: BrowserEnvelope;
    id: string;
    /**
     * Compatibility alias for clients written before templates could target multiple roles.
     */
    memberRole: string;
    memberRoles: Array<string>;
};

export type BrowserExecutionLogResponse = {
    complete: boolean;
    content: string;
    sizeBytes: number;
    stream: string;
    truncated: boolean;
};

export type BrowserMutationRequest = {
    [key: string]: never;
};

export type BrowserPreferencesView = {
    apiVersion: string;
    onboardingDismissed: boolean;
    revision: number;
    theme?: null | BrowserTheme;
};

export type BrowserRole = 'user' | 'admin';

export type BrowserRunFacets = {
    phase: BrowserRunPhaseFacets;
};

export type BrowserRunPhaseFacets = {
    cancelled: number;
    failed: number;
    parked: number;
    queued: number;
    running: number;
    submitted: number;
    succeeded: number;
};

export type BrowserRunResponse = {
    apiVersion: string;
    run: BrowserRunView;
};

export type BrowserRunStage = {
    displayName: string;
    id: string;
    state: BrowserRunStageState;
    steps: Array<BrowserRunStep>;
};

export type BrowserRunStageState = 'pending' | 'running' | 'succeeded' | 'failed' | 'cancelled';

export type BrowserRunStep = {
    displayName: string;
    id: string;
    logStreams: Array<string>;
    state: BrowserRunStageState;
};

export type BrowserRunTimelineEvent = {
    at: string;
    kind: 'phase';
    phase: TaskPhase;
} | {
    at: string;
    kind: 'finalizationRequested';
} | {
    at: string;
    kind: 'finalized';
} | {
    at: string;
    details: unknown;
    kind: 'stage';
    stage: string;
};

export type BrowserRunTimelineResponse = {
    apiVersion: string;
    events: Array<BrowserRunTimelineEvent>;
    taskUid: string;
};

export type BrowserRunTrigger = {
    actor: string;
    callerWorkflow: string;
    event: string;
    provider: string;
    ref: string;
    repository: string;
    runAttempt: number;
    runId: string;
    runUrl: string;
    sha: string;
};

export type BrowserRunView = {
    codingAgentRuntime: string;
    createdAt: string;
    errorCategory?: string | null;
    finalizationRequested: boolean;
    finalized: boolean;
    observedSpend?: null | AgentRunSpendView;
    phase: TaskPhase;
    runtimeOwnership: RuntimeOwnership;
    runtimeUid?: string | null;
    stages: Array<BrowserRunStage>;
    taskUid: string;
    trigger?: null | BrowserRunTrigger;
    updatedAt: string;
    userEnvelopeDigest?: string | null;
    userEnvelopeInstanceId?: string | null;
    userEnvelopeRevision?: number | null;
    workflow: string;
    workflowDigest?: string | null;
    workflowName?: string | null;
    workflowVersion?: number | null;
};

export type BrowserTheme = 'light' | 'dark' | 'system';

export type Budget = {
    currency: string;
    monthlyLimit: string;
    singleRunLimit?: string | null;
};

export type BudgetIncrease = {
    amount: string;
};

export type BudgetRequirement = {
    currency: Currency;
    monthlyLimit: Decimal;
    singleRunLimit?: null | Decimal;
};

/**
 * Minimum stable person binding carried by a live AgentRuntime.
 *
 * This deliberately excludes email and external identity-provider claims. In v1, an acting
 * person is always the accountable owner; pure services omit `acting_user_id`.
 */
export type CanonicalAuthorityBinding = {
    actingUserId?: null | CanonicalUserId;
    ownerUserId: CanonicalUserId;
    schemaVersion: string;
};

/**
 * Opaque, immutable identifier allocated by Steward for one person.
 * The value deliberately contains no email, identity-provider subject, or organization name.
 */
export type CanonicalUserId = string;

export type CapabilityCatalog = {
    catalogs: Array<CapabilityProviderCatalog>;
    models: Array<ModelRef>;
    schemaVersion: string;
    tools: Array<CapabilityTool>;
};

export type CapabilityProviderCatalog = {
    available: boolean;
    catalogId: string;
    provider: string;
    version: string;
};

export type CapabilityTool = {
    accessClass: ToolAccessClass;
    action: string;
    provider: string;
    resource: string;
};

export type ClosureEntry = {
    digest: ContentDigest;
    kind: ClosureEntryKind;
    path: RelativePath;
    sizeBytes: number;
};

export type ClosureEntryKind = 'task_definition' | 'prompt' | 'instruction_skill' | 'instructions' | 'asset';

export type ConnectionOperationErrorResponse = {
    apiVersion: string;
    error: string;
};

export type ConnectionPhase = 'disconnected' | 'connecting' | 'connected' | 'reauth_required' | 'unavailable';

export type ConnectionStatusResponse = {
    apiVersion: string;
    provider: string;
    status: ProviderConnectionStatus;
};

export type ConnectionsCollectionResponse = {
    apiVersion: string;
    available: Array<AvailableProviderConnection>;
    connections: Array<ProviderConnectionView>;
};

export type ContentDigest = string;

export type CreateEnvelopeRequestBody = {
    idempotencyKey: string;
    requestedEnvelope: BrowserEnvelope;
    templateId: string;
    templateRevision: number;
};

export type CreateRuntimeRequest = {
    name: string;
    spec: AgentRuntimeSpec;
};

export type Currency = string;

export type Decimal = string;

export type DiagnosticsRequest = {
    executionLog?: ExecutionLogMode;
};

export type DirectAdmissionDelta = {
    ceiling: Decimal;
    currency: Currency;
    dimension: 'budget';
    requested: Decimal;
} | {
    ceiling: Decimal;
    currency: Currency;
    dimension: 'singleRunBudget';
    requested?: null | Decimal;
} | {
    ceiling: Decimal;
    dimension: 'runtimeMinutes';
    requested?: null | Decimal;
} | {
    ceiling: Duration;
    dimension: 'ttl';
    requested: Duration;
} | {
    ceiling: Array<ModelRequirement>;
    dimension: 'models';
    requested: Array<ModelRequirement>;
} | {
    ceiling: Array<ToolRequirement>;
    dimension: 'tools';
    requested: Array<ToolRequirement>;
} | {
    ceiling: Array<RunnerPlatform>;
    dimension: 'runnerPlatforms';
    requested: Array<RunnerPlatform>;
} | {
    ceiling?: null | ResourceQuantity;
    dimension: 'runnerMemory';
    requested: ResourceQuantity;
} | {
    ceiling?: null | ResourceQuantity;
    dimension: 'runnerCompute';
    requested: ResourceQuantity;
} | {
    ceiling?: null | ResourceQuantity;
    dimension: 'runnerStorage';
    requested: ResourceQuantity;
};

export type DirectRequirements = {
    authority: AuthorityRequirements;
};

export type DirectRuntimeOwnership = 'provisioned' | 'adopted';

export type DirectTaskBindingEvidence = {
    closure: PackageClosure;
    closureDigest: ContentDigest;
    diagnostics: DiagnosticsRequest;
    effectiveRequirements: DirectRequirements;
    envelope: EnvelopeEvidence;
    invocation: ResolvedSource;
    package: ResolvedSource;
    schemaVersion: string;
    sourceProvenance: SourceProvenance;
    taskUid: Uuid;
};

export type DirectTaskPhase = 'submitted' | 'parked' | 'queued' | 'running' | 'succeeded' | 'failed' | 'cancelled';

export type DirectTaskStatusResponse = {
    contractVersion: string;
    deltas?: Array<DirectAdmissionDelta>;
    diagnostics: DiagnosticsRequest;
    evidence: DirectTaskBindingEvidence;
    failureReason?: null | BoundedText;
    finalized: boolean;
    phase: DirectTaskPhase;
    runtimeOwnership: DirectRuntimeOwnership;
    runtimeUid?: null | BoundedText;
    taskUid: Uuid;
};

export type DirectTaskSubmission = {
    contractVersion: string;
    invocationPath: RelativePath;
};

export type DisconnectConnectionRequest = {
    confirm: boolean;
};

export type Duration = string;

export type Email = string;

export type EnvelopeDigest = string;

export type EnvelopeEvidence = {
    digest: EnvelopeDigest;
    revision: number;
    uid: Uuid;
};

export type EnvelopeRequestHistoryEvent = {
    actor: string;
    at: string;
    evidenceUrl?: string | null;
    expiresAt?: string | null;
    rationale?: string | null;
    reason?: string | null;
    status: EnvelopeRequestStatus;
};

export type EnvelopeRequestResponse = {
    apiVersion: string;
    request: UserEnvelopeRequest;
};

export type EnvelopeRequestStatus = 'pending' | 'approved' | 'rejected' | 'provisioned' | 'stale' | 'conflict';

export type EnvelopeRequestsResponse = {
    apiVersion: string;
    nextCursor?: string | null;
    requests: Array<UserEnvelopeRequest>;
};

export type EnvelopeSpendUsage = {
    currency: string;
    limit: string;
    observed: string;
    observedAt: string;
};

export type EnvelopeTemplatesResponse = {
    apiVersion: string;
    templates: Array<AvailableEnvelopeTemplate>;
};

export type EnvelopeUsagePeriod = {
    end: string;
    start: string;
};

export type EnvelopeUsageView = {
    availability: AgentRunDataStatus;
    period: EnvelopeUsagePeriod;
    spend?: null | EnvelopeSpendUsage;
};

export type EscalationDenyRequest = {
    rationale: string;
};

export type EscalationDimension = 'llm_spend' | 'runtime_minutes';

export type EscalationMeter = {
    dimension: EscalationDimension;
    exhausted: boolean;
    limit: string;
    observedAt: string;
    unit: string;
    used: string;
};

export type EscalationPeriod = {
    end: string;
    start: string;
};

export type EscalationTopUpRequest = {
    amount: string;
    dimension: EscalationDimension;
    rationale: string;
    validUntil: string;
};

export type EscalationView = {
    blockedTaskUid: string;
    envelopeInstanceId: string;
    meters: Array<EscalationMeter>;
    parkedAt: string;
    period: EscalationPeriod;
};

export type ExactGitCommit = string;

export type ExecutionBindingAdvertisement = {
    agentRef: string;
    displayName?: string | null;
};

export type ExecutionLogMode = 'off' | 'full';

export type GeneratedGithubActionsWorkflow = {
    contentType: string;
    schemaVersion: string;
    sha256: string;
    suggestedPath: string;
    yaml: string;
};

export type GithubActionsWorkflowResponse = {
    apiVersion: string;
    workflow: GeneratedGithubActionsWorkflow;
};

/**
 * A Kubernetes resource quantity. Admission validates the supported unit family for each
 * resource dimension before it becomes authority.
 */
export type KubernetesQuantity = string;

export type LegacyTaskStatusResponse = {
    deltas?: Array<TaskAdmissionDelta>;
    failureReason?: string | null;
    finalized: boolean;
    phase: TaskPhase;
    runtimeOwnership: RuntimeOwnership;
    runtimeUid?: string | null;
    taskUid: string;
};

export type ModelRef = {
    model: string;
    provider: string;
};

export type ModelRequirement = {
    model: BoundedText;
    provider: Slug;
};

export type MyRunsResponse = {
    apiVersion: string;
    facets: BrowserRunFacets;
    nextCursor?: string | null;
    runs: Array<BrowserRunView>;
};

export type PackageClosure = {
    contractVersion: string;
    entries: Array<ClosureEntry>;
    entryPoint: RelativePath;
};

export type Principal = {
    acting_user: Email;
    kind: 'user';
} | {
    acting_user?: null | Email;
    kind: 'service';
    name: string;
};

export type ProviderConnectionStatus = {
    accountEmail?: string | null;
    activeCredentialExpiresAt?: string | null;
    expiresAt?: string | null;
    phase: ConnectionPhase;
    renewalCredentialExpiresAt?: string | null;
    scopesGranted: Array<string>;
    scopesMissing: Array<string>;
    scopesRequired: Array<string>;
};

export type ProviderConnectionView = {
    displayName: string;
    provider: string;
    status: ProviderConnectionStatus;
};

export type PublishWorkflowRequest = {
    agent: string;
    displayName: string;
    name: string;
    prompt: string;
};

export type PublishWorkflowVersionRequest = {
    agent: string;
    displayName: string;
    prompt: string;
};

export type PublishedWorkflowOption = {
    agent: string;
    displayName: string;
    name: string;
    sample: boolean;
    version: number;
};

export type PublishedWorkflowsResponse = {
    apiVersion: string;
    workflows: Array<PublishedWorkflowOption>;
};

export type RejectEnvelopeRequestBody = {
    reason?: string | null;
};

export type RelativePath = string;

export type RenderGithubActionsWorkflowBody = {
    workflow: string;
};

export type RepositoryUrl = string;

export type RerunPendingResponse = {
    apiVersion: string;
    retryAfterMs: number;
    state: string;
};

export type RerunRequest = {
    idempotencyKey: string;
};

export type RerunResponse = {
    apiVersion: string;
    taskUid: string;
};

export type ResolvedSource = {
    commit: ExactGitCommit;
    contentDigest: ContentDigest;
    path: RelativePath;
    repository: RepositoryUrl;
    repositoryId: StableProviderId;
    repositoryOwnerId: StableProviderId;
};

export type ResourceQuantity = string;

/**
 * Canonical platform names accepted by the governed runner contract.
 */
export type RunnerPlatform = 'linux' | 'mac' | 'windows';

export type RunnerRequirement = {
    compute?: null | ResourceQuantity;
    memory?: null | ResourceQuantity;
    platforms: Array<RunnerPlatform>;
    storage?: null | ResourceQuantity;
};

export type RunnerRequirements = {
    compute?: null | KubernetesQuantity;
    memory?: null | KubernetesQuantity;
    platforms?: Array<RunnerPlatform>;
    storage?: null | KubernetesQuantity;
};

export type RuntimeOwnership = 'provisioned' | 'adopted';

export type SessionPrincipalResponse = {
    displayEmail: Email;
    displayName: string;
    userId: CanonicalUserId;
};

export type SessionResponse = {
    apiVersion: string;
    csrf: string;
    memberRoles: Array<string>;
    principal: SessionPrincipalResponse;
    role: BrowserRole;
    surfaces: Array<string>;
};

export type Slug = string;

export type SourceProvenance = {
    actor: BoundedText;
    actorId: StableProviderId;
    callerWorkflow: WorkflowIdentity;
    contractVersion: string;
    event: BoundedText;
    provider: SourceProvider;
    ref: BoundedRef;
    repository: TriggerRepository;
    reusableWorkflow: WorkflowIdentity;
    run: WorkflowRun;
    triggeredSha: ExactGitCommit;
};

export type SourceProvider = 'github';

export type StableProviderId = string;

export type StartConnectionResponse = {
    apiVersion: string;
    /**
     * One-time HTTPS destination. It must not be persisted or logged by clients.
     */
    authorizationUrl: string;
    /**
     * Conservative expiry for MCP-GW's pinned OAuth state lifetime plus clock skew.
     */
    expiresAt: string;
    provider: string;
};

/**
 * Machine-readable shape of an admission delta returned in Task status.
 */
export type TaskAdmissionDelta = {
    ceiling: string;
    currency: string;
    dimension: 'budget';
    requested: string;
} | {
    ceiling: string;
    dimension: 'ttl';
    requested: string;
} | {
    ceiling: Array<ModelRef>;
    dimension: 'models';
    requested: Array<ModelRef>;
} | {
    ceiling: Array<ToolGrant>;
    dimension: 'tools';
    requested: Array<ToolGrant>;
};

/**
 * Opaque tar archive, limited to 67,108,864 raw bytes
 */
export type TaskArchive = Blob | File;

export type TaskCreateRequest = TaskSubmissionRequest | DirectTaskSubmission;

export type TaskErrorResponse = {
    error: string;
};

/**
 * Durable lifecycle state for one single-shot governed task.
 */
export type TaskPhase = 'submitted' | 'parked' | 'queued' | 'running' | 'succeeded' | 'failed' | 'cancelled';

export type TaskStatusResponse = LegacyTaskStatusResponse | DirectTaskStatusResponse;

export type TaskSubmissionRequest = {
    agentRuntimeUid?: string | null;
    /**
     * Optional compatibility assertion for an unversioned legacy Workflow.
     * Steward selects the runtime from its own Workflow catalog when this is
     * omitted and rejects any supplied value that does not match the catalog.
     * Versioned Workflows always reject this field.
     */
    codingAgentRuntime?: string | null;
    workflow: string;
};

export type ToolAccessClass = 'read' | 'write' | 'destructive';

export type ToolGrant = {
    action: string;
    provider: string;
    resource: string;
};

export type ToolRequirement = {
    action: BoundedText;
    provider: Slug;
    resource: BoundedText;
};

export type TriggerRepository = {
    id: StableProviderId;
    name: BoundedText;
    ownerId: StableProviderId;
};

export type UpdateBrowserPreferences = {
    onboardingDismissed?: boolean | null;
    theme?: null | BrowserTheme;
};

export type UserEnvelopeRequest = {
    approvalId?: string | null;
    approvedEnvelope?: null | BrowserEnvelope;
    createdAt: string;
    envelopeDigest?: string | null;
    envelopeInstanceId?: string | null;
    history: Array<EnvelopeRequestHistoryEvent>;
    id: string;
    reason?: string | null;
    requestedEnvelope: BrowserEnvelope;
    status: EnvelopeRequestStatus;
    statusActor: string;
    statusAt: string;
    statusTemplateRevision: number;
    templateId: string;
    templateRevision: number;
    usage?: null | EnvelopeUsageView;
};

export type Uuid = string;

export type WorkflowIdentity = {
    ref: BoundedRef;
    sha: ExactGitCommit;
};

export type WorkflowListResponse = {
    /**
     * Exact logical agent references from the deployment-owned execution catalog.
     */
    agents: Array<ExecutionBindingAdvertisement>;
    apiVersion: string;
    workflows: Array<WorkflowRevisionView>;
};

export type WorkflowRevisionResponse = {
    apiVersion: string;
    workflow: WorkflowRevisionView;
};

export type WorkflowRevisionView = {
    agent: string;
    contentDigest: string;
    displayName: string;
    name: string;
    prompt: string;
    publishedAt: string;
    publishedBy: string;
    version: number;
};

export type WorkflowRun = {
    attempt: number;
    id: StableProviderId;
};

export type AllRunsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        cursor?: string;
        phase?: TaskPhase;
        workflow?: string;
        ownerUserId?: CanonicalUserId;
        runtimeUid?: string;
    };
    url: '/admin/api/v1/all-runs';
};

export type AllRunsErrors = {
    /**
     * Run query is invalid
     */
    400: unknown;
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role is required
     */
    403: unknown;
    /**
     * Run history is unavailable
     */
    503: unknown;
};

export type AllRunsResponses = {
    200: AllRunsResponse;
};

export type AllRunsResponse2 = AllRunsResponses[keyof AllRunsResponses];

export type AllRunData = {
    body?: never;
    path: {
        task_uid: string;
    };
    query?: never;
    url: '/admin/api/v1/all-runs/{task_uid}';
};

export type AllRunErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role is required
     */
    403: unknown;
    /**
     * Run was not found
     */
    404: unknown;
    /**
     * Run history is unavailable
     */
    503: unknown;
};

export type AllRunResponses = {
    200: BrowserRunResponse;
};

export type AllRunResponse = AllRunResponses[keyof AllRunResponses];

export type AllRunExecutionLogData = {
    body?: never;
    path: {
        task_uid: string;
        /**
         * Exact execution stream: stdout or stderr
         */
        stream: string;
    };
    query?: {
        /**
         * Zero-based byte offset
         */
        after?: number;
    };
    url: '/admin/api/v1/all-runs/{task_uid}/logs/{stream}';
};

export type AllRunExecutionLogErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role is required
     */
    403: unknown;
    /**
     * Execution log was not found
     */
    404: unknown;
    /**
     * Run history is unavailable
     */
    503: unknown;
};

export type AllRunExecutionLogResponses = {
    200: BrowserExecutionLogResponse;
};

export type AllRunExecutionLogResponse = AllRunExecutionLogResponses[keyof AllRunExecutionLogResponses];

export type AllRunTimelineData = {
    body?: never;
    path: {
        task_uid: string;
    };
    query?: never;
    url: '/admin/api/v1/all-runs/{task_uid}/timeline';
};

export type AllRunTimelineErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role is required
     */
    403: unknown;
    /**
     * Run was not found
     */
    404: unknown;
    /**
     * Run history is unavailable
     */
    503: unknown;
};

export type AllRunTimelineResponses = {
    200: BrowserRunTimelineResponse;
};

export type AllRunTimelineResponse = AllRunTimelineResponses[keyof AllRunTimelineResponses];

export type ListAdminApprovalsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/api/v1/approvals';
};

export type ListAdminApprovalsErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role is required
     */
    403: unknown;
    /**
     * Approvals are unavailable
     */
    503: unknown;
};

export type ListAdminApprovalsResponses = {
    200: BrowserApprovalsResponse;
};

export type ListAdminApprovalsResponse = ListAdminApprovalsResponses[keyof ListAdminApprovalsResponses];

export type ApproveAdminApprovalData = {
    body: ApprovalRequest;
    headers: {
        'X-Steward-CSRF': string;
    };
    path: {
        approval_id: string;
    };
    query?: never;
    url: '/admin/api/v1/approvals/{approval_id}/approve';
};

export type ApproveAdminApprovalErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role, origin, fetch metadata, or CSRF proof is invalid
     */
    403: unknown;
    /**
     * Approval was not found
     */
    404: unknown;
    /**
     * Approval or its bound runtime is stale
     */
    409: unknown;
    /**
     * Approval evidence is invalid
     */
    422: unknown;
    /**
     * Approval authority is unavailable
     */
    503: unknown;
};

export type ApproveAdminApprovalResponses = {
    /**
     * Approval was applied through the existing governed approval path
     */
    204: void;
};

export type ApproveAdminApprovalResponse = ApproveAdminApprovalResponses[keyof ApproveAdminApprovalResponses];

export type FileAdminApprovalDecisionData = {
    body: BrowserMutationRequest;
    headers: {
        'X-Steward-CSRF': string;
    };
    path: {
        approval_id: string;
    };
    query?: never;
    url: '/admin/api/v1/approvals/{approval_id}/file';
};

export type FileAdminApprovalDecisionErrors = {
    /**
     * Mutation JSON is malformed
     */
    400: unknown;
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role, origin, fetch metadata, or CSRF proof is invalid
     */
    403: unknown;
    /**
     * Approval was not found
     */
    404: unknown;
    /**
     * Decision filing is already active or conflicts
     */
    409: unknown;
    /**
     * Decision filing is unavailable
     */
    503: unknown;
};

export type FileAdminApprovalDecisionResponses = {
    200: BrowserDecisionReferenceResponse;
};

export type FileAdminApprovalDecisionResponse = FileAdminApprovalDecisionResponses[keyof FileAdminApprovalDecisionResponses];

export type GetAdminCapabilitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/api/v1/capabilities';
};

export type GetAdminCapabilitiesErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role is required
     */
    403: unknown;
};

export type GetAdminCapabilitiesResponses = {
    200: CapabilityCatalog;
};

export type GetAdminCapabilitiesResponse = GetAdminCapabilitiesResponses[keyof GetAdminCapabilitiesResponses];

export type ConnectionStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/api/v1/connections/github';
};

export type ConnectionStatusErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Provider state is invalid
     */
    502: unknown;
    503: ConnectionStatusResponse;
};

export type ConnectionStatusError = ConnectionStatusErrors[keyof ConnectionStatusErrors];

export type ConnectionStatusResponses = {
    200: ConnectionStatusResponse;
};

export type ConnectionStatusResponse2 = ConnectionStatusResponses[keyof ConnectionStatusResponses];

export type DisconnectConnectionData = {
    body: DisconnectConnectionRequest;
    headers: {
        'X-Steward-CSRF': string;
    };
    path?: never;
    query?: never;
    url: '/admin/api/v1/connections/github/disconnect';
};

export type DisconnectConnectionErrors = {
    /**
     * Explicit confirmation is required
     */
    400: unknown;
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Origin, fetch metadata, or CSRF proof is invalid
     */
    403: unknown;
    /**
     * An OAuth flow is still pending
     */
    409: ConnectionOperationErrorResponse;
    /**
     * Provider state is invalid
     */
    502: unknown;
    /**
     * Connection broker is unavailable
     */
    503: unknown;
};

export type DisconnectConnectionError = DisconnectConnectionErrors[keyof DisconnectConnectionErrors];

export type DisconnectConnectionResponses = {
    /**
     * Connection was disconnected
     */
    204: void;
};

export type DisconnectConnectionResponse = DisconnectConnectionResponses[keyof DisconnectConnectionResponses];

export type StartConnectionData = {
    body: BrowserMutationRequest;
    headers: {
        'X-Steward-CSRF': string;
    };
    path?: never;
    query?: never;
    url: '/admin/api/v1/connections/github/start';
};

export type StartConnectionErrors = {
    /**
     * Mutation JSON is malformed
     */
    400: unknown;
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Origin, fetch metadata, or CSRF proof is invalid
     */
    403: unknown;
    /**
     * Provider continuation is invalid
     */
    502: unknown;
    /**
     * Connection broker is unavailable
     */
    503: unknown;
};

export type StartConnectionResponses = {
    200: StartConnectionResponse;
};

export type StartConnectionResponse2 = StartConnectionResponses[keyof StartConnectionResponses];

export type ApproveAdminEnvelopeRequestData = {
    body: ApproveEnvelopeRequestBody;
    headers: {
        'X-Steward-CSRF': string;
    };
    path: {
        request_id: string;
    };
    query?: never;
    url: '/admin/api/v1/envelope-requests/{request_id}/approve';
};

export type ApproveAdminEnvelopeRequestErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role, origin, fetch metadata, or CSRF proof is invalid
     */
    403: unknown;
    /**
     * Envelope request was not found
     */
    404: unknown;
    /**
     * Envelope request or template revision is stale or already decided differently
     */
    409: unknown;
    /**
     * Envelope request authority is unavailable
     */
    503: unknown;
};

export type ApproveAdminEnvelopeRequestResponses = {
    200: BrowserEnvelopeRequestDecisionResponse;
};

export type ApproveAdminEnvelopeRequestResponse = ApproveAdminEnvelopeRequestResponses[keyof ApproveAdminEnvelopeRequestResponses];

export type FileAdminEnvelopeRequestData = {
    body: BrowserMutationRequest;
    headers: {
        'X-Steward-CSRF': string;
    };
    path: {
        request_id: string;
    };
    query?: never;
    url: '/admin/api/v1/envelope-requests/{request_id}/file';
};

export type FileAdminEnvelopeRequestErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role, origin, fetch metadata, or CSRF proof is invalid
     */
    403: unknown;
    /**
     * Envelope request was not found
     */
    404: unknown;
    /**
     * Envelope request is no longer governed by the current template revision
     */
    409: unknown;
    /**
     * Envelope request does not exceed its template ceiling
     */
    422: unknown;
    /**
     * Envelope request or decision channel is unavailable
     */
    503: unknown;
};

export type FileAdminEnvelopeRequestResponses = {
    200: BrowserEnvelopeRequestDecisionReferenceResponse;
};

export type FileAdminEnvelopeRequestResponse = FileAdminEnvelopeRequestResponses[keyof FileAdminEnvelopeRequestResponses];

export type RejectAdminEnvelopeRequestData = {
    body: RejectEnvelopeRequestBody;
    headers: {
        'X-Steward-CSRF': string;
    };
    path: {
        request_id: string;
    };
    query?: never;
    url: '/admin/api/v1/envelope-requests/{request_id}/reject';
};

export type RejectAdminEnvelopeRequestErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role, origin, fetch metadata, or CSRF proof is invalid
     */
    403: unknown;
    /**
     * Envelope request was not found
     */
    404: unknown;
    /**
     * Envelope request was already decided differently
     */
    409: unknown;
    /**
     * Rejection reason is invalid
     */
    422: unknown;
    /**
     * Envelope request authority is unavailable
     */
    503: unknown;
};

export type RejectAdminEnvelopeRequestResponses = {
    200: BrowserEnvelopeRequestDecisionResponse;
};

export type RejectAdminEnvelopeRequestResponse = RejectAdminEnvelopeRequestResponses[keyof RejectAdminEnvelopeRequestResponses];

export type ListAdminEnvelopeTemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/api/v1/envelope-templates';
};

export type ListAdminEnvelopeTemplatesErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role is required
     */
    403: unknown;
    /**
     * Envelope templates are unavailable
     */
    503: unknown;
};

export type ListAdminEnvelopeTemplatesResponses = {
    200: BrowserEnvelopeTemplateListResponse;
};

export type ListAdminEnvelopeTemplatesResponse = ListAdminEnvelopeTemplatesResponses[keyof ListAdminEnvelopeTemplatesResponses];

export type GetAdminEnvelopeTemplateData = {
    body?: never;
    path: {
        member_role: string;
    };
    query?: never;
    url: '/admin/api/v1/envelope-templates/{member_role}';
};

export type GetAdminEnvelopeTemplateErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role is required
     */
    403: unknown;
    /**
     * Envelope template was not found
     */
    404: unknown;
    /**
     * Envelope templates are unavailable
     */
    503: unknown;
};

export type GetAdminEnvelopeTemplateResponses = {
    200: BrowserEnvelopeTemplateResponse;
};

export type GetAdminEnvelopeTemplateResponse = GetAdminEnvelopeTemplateResponses[keyof GetAdminEnvelopeTemplateResponses];

export type AuthorAdminEnvelopeTemplateData = {
    body: BrowserEnvelope;
    headers: {
        'X-Steward-CSRF': string;
    };
    path: {
        member_role: string;
    };
    query?: never;
    url: '/admin/api/v1/envelope-templates/{member_role}';
};

export type AuthorAdminEnvelopeTemplateErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role, origin, fetch metadata, or CSRF proof is invalid
     */
    403: unknown;
    /**
     * Envelope revision is not newer than the current revision
     */
    409: unknown;
    /**
     * Template identifier, envelope, or deployed capability selection is invalid
     */
    422: unknown;
    /**
     * Envelope templates are unavailable
     */
    503: unknown;
};

export type AuthorAdminEnvelopeTemplateResponses = {
    201: BrowserEnvelopeTemplateResponse;
};

export type AuthorAdminEnvelopeTemplateResponse = AuthorAdminEnvelopeTemplateResponses[keyof AuthorAdminEnvelopeTemplateResponses];

export type PutAdminEnvelopeTemplateData = {
    body: AuthorEnvelopeTemplateBody;
    headers: {
        'X-Steward-CSRF': string;
    };
    path: {
        member_role: string;
    };
    query?: never;
    url: '/admin/api/v1/envelope-templates/{member_role}';
};

export type PutAdminEnvelopeTemplateErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role, origin, fetch metadata, or CSRF proof is invalid
     */
    403: unknown;
    /**
     * Envelope revision is not newer than the current revision
     */
    409: unknown;
    /**
     * Member role, envelope, or deployed capability selection is invalid
     */
    422: unknown;
    /**
     * Envelope templates are unavailable
     */
    503: unknown;
};

export type PutAdminEnvelopeTemplateResponses = {
    201: BrowserEnvelopeTemplateResponse;
};

export type PutAdminEnvelopeTemplateResponse = PutAdminEnvelopeTemplateResponses[keyof PutAdminEnvelopeTemplateResponses];

export type DenyAdminEscalationData = {
    body: EscalationDenyRequest;
    headers: {
        'X-Steward-CSRF': string;
    };
    path: {
        escalation_id: string;
    };
    query?: never;
    url: '/admin/api/v1/escalations/{escalation_id}/deny';
};

export type DenyAdminEscalationErrors = {
    /**
     * Denial rationale is invalid
     */
    400: unknown;
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role or mutation proof is invalid
     */
    403: unknown;
    /**
     * Escalation was not found
     */
    404: unknown;
    /**
     * Escalation was already decided differently
     */
    409: unknown;
    /**
     * Escalation authority is unavailable
     */
    503: unknown;
};

export type DenyAdminEscalationResponses = {
    200: AdminRequestResponse;
};

export type DenyAdminEscalationResponse = DenyAdminEscalationResponses[keyof DenyAdminEscalationResponses];

export type TopUpAdminEscalationData = {
    body: EscalationTopUpRequest;
    headers: {
        'X-Steward-CSRF': string;
    };
    path: {
        escalation_id: string;
    };
    query?: never;
    url: '/admin/api/v1/escalations/{escalation_id}/top-up';
};

export type TopUpAdminEscalationErrors = {
    /**
     * Top-up is invalid or runtime-minutes enforcement is unavailable
     */
    400: unknown;
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role or mutation proof is invalid
     */
    403: unknown;
    /**
     * Escalation or bound runtime was not found
     */
    404: unknown;
    /**
     * Escalation was already decided differently
     */
    409: unknown;
    /**
     * Escalation authority is unavailable
     */
    503: unknown;
};

export type TopUpAdminEscalationResponses = {
    200: AdminRequestResponse;
};

export type TopUpAdminEscalationResponse = TopUpAdminEscalationResponses[keyof TopUpAdminEscalationResponses];

export type ListAdminRequestsData = {
    body?: never;
    path?: never;
    query?: {
        state?: string;
        kind?: string;
        cursor?: string;
        limit?: number;
    };
    url: '/admin/api/v1/requests';
};

export type ListAdminRequestsErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role is required
     */
    403: unknown;
    /**
     * Filter, cursor, or limit is invalid
     */
    422: unknown;
    /**
     * Request read model is unavailable
     */
    503: unknown;
};

export type ListAdminRequestsResponses = {
    200: AdminRequestsResponse;
};

export type ListAdminRequestsResponse = ListAdminRequestsResponses[keyof ListAdminRequestsResponses];

export type GetAdminRequestsSummaryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/api/v1/requests/summary';
};

export type GetAdminRequestsSummaryErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role is required
     */
    403: unknown;
    /**
     * Request read model is unavailable
     */
    503: unknown;
};

export type GetAdminRequestsSummaryResponses = {
    200: AdminRequestsSummaryResponse;
};

export type GetAdminRequestsSummaryResponse = GetAdminRequestsSummaryResponses[keyof GetAdminRequestsSummaryResponses];

export type GetAdminRequestData = {
    body?: never;
    path: {
        request_id: string;
    };
    query?: never;
    url: '/admin/api/v1/requests/{request_id}';
};

export type GetAdminRequestErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role is required
     */
    403: unknown;
    /**
     * Request was not found
     */
    404: unknown;
    /**
     * Request read model is unavailable
     */
    503: unknown;
};

export type GetAdminRequestResponses = {
    200: AdminRequestResponse;
};

export type GetAdminRequestResponse = GetAdminRequestResponses[keyof GetAdminRequestResponses];

export type AgentRunsContractData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page size from 1 through 100; defaults to 50
         */
        limit?: number;
        /**
         * Task UID at the immutable page boundary
         */
        cursor?: string;
        /**
         * Exact Task lifecycle phase
         */
        phase?: string;
        /**
         * Exact workflow name
         */
        workflow?: string;
    };
    url: '/admin/api/v1/runs';
};

export type AgentRunsContractErrors = {
    /**
     * Query or cursor is invalid
     */
    400: unknown;
    /**
     * Identity assertion is missing or invalid
     */
    401: unknown;
    /**
     * Exact Steward administrator authority is absent
     */
    403: unknown;
    /**
     * Agent-run persistence is unavailable
     */
    503: unknown;
};

export type AgentRunsContractResponses = {
    /**
     * Privacy-bounded authoritative Agent Runs page
     */
    200: AgentRunsResponse;
};

export type AgentRunsContractResponse = AgentRunsContractResponses[keyof AgentRunsContractResponses];

export type AgentRunContractData = {
    body?: never;
    path: {
        /**
         * Canonical Steward Task UID
         */
        taskUid: string;
    };
    query?: never;
    url: '/admin/api/v1/runs/{taskUid}';
};

export type AgentRunContractErrors = {
    /**
     * Identity assertion is missing or invalid
     */
    401: unknown;
    /**
     * Exact Steward administrator authority is absent
     */
    403: unknown;
    /**
     * Agent Run does not exist
     */
    404: unknown;
    /**
     * Agent-run persistence is unavailable
     */
    503: unknown;
};

export type AgentRunContractResponses = {
    /**
     * Privacy-bounded authoritative Agent Run
     */
    200: AgentRunResponse;
};

export type AgentRunContractResponse = AgentRunContractResponses[keyof AgentRunContractResponses];

export type AgentRunTimelineContractData = {
    body?: never;
    path: {
        /**
         * Canonical Steward Task UID
         */
        taskUid: string;
    };
    query?: never;
    url: '/admin/api/v1/runs/{taskUid}/timeline';
};

export type AgentRunTimelineContractErrors = {
    /**
     * Identity assertion is missing or invalid
     */
    401: unknown;
    /**
     * Exact Steward administrator authority is absent
     */
    403: unknown;
    /**
     * Agent Run does not exist
     */
    404: unknown;
    /**
     * Agent-run persistence is unavailable
     */
    503: unknown;
};

export type AgentRunTimelineContractResponses = {
    /**
     * Append-only Task lifecycle with recorded/backfilled provenance
     */
    200: AgentRunTimelineResponse;
};

export type AgentRunTimelineContractResponse = AgentRunTimelineContractResponses[keyof AgentRunTimelineContractResponses];

export type SessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/api/v1/session';
};

export type SessionErrors = {
    /**
     * Opaque browser session is missing, invalid, or expired
     */
    401: unknown;
    /**
     * Browser session registry is unavailable
     */
    503: unknown;
};

export type SessionResponses = {
    /**
     * Opaque browser session identity, authorized modes, surfaces, and CSRF value
     */
    200: SessionResponse;
};

export type SessionResponse2 = SessionResponses[keyof SessionResponses];

export type ListAdminWorkflowsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/api/v1/workflows';
};

export type ListAdminWorkflowsErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role is required
     */
    403: unknown;
    /**
     * Workflow store is unavailable
     */
    503: unknown;
};

export type ListAdminWorkflowsResponses = {
    200: WorkflowListResponse;
};

export type ListAdminWorkflowsResponse = ListAdminWorkflowsResponses[keyof ListAdminWorkflowsResponses];

export type PublishAdminWorkflowData = {
    body: PublishWorkflowRequest;
    headers: {
        'X-Steward-CSRF': string;
    };
    path?: never;
    query?: never;
    url: '/admin/api/v1/workflows';
};

export type PublishAdminWorkflowErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role or mutation proof is invalid
     */
    403: unknown;
    /**
     * Workflow name already exists
     */
    409: unknown;
    /**
     * Workflow content is invalid
     */
    422: unknown;
    /**
     * Workflow store is unavailable
     */
    503: unknown;
};

export type PublishAdminWorkflowResponses = {
    201: WorkflowRevisionResponse;
};

export type PublishAdminWorkflowResponse = PublishAdminWorkflowResponses[keyof PublishAdminWorkflowResponses];

export type PublishAdminWorkflowVersionData = {
    body: PublishWorkflowVersionRequest;
    headers: {
        'X-Steward-CSRF': string;
    };
    path: {
        name: string;
    };
    query?: never;
    url: '/admin/api/v1/workflows/{name}/versions';
};

export type PublishAdminWorkflowVersionErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role or mutation proof is invalid
     */
    403: unknown;
    /**
     * Workflow was not found
     */
    404: unknown;
    /**
     * Workflow content is invalid
     */
    422: unknown;
    /**
     * Workflow store is unavailable
     */
    503: unknown;
};

export type PublishAdminWorkflowVersionResponses = {
    201: WorkflowRevisionResponse;
};

export type PublishAdminWorkflowVersionResponse = PublishAdminWorkflowVersionResponses[keyof PublishAdminWorkflowVersionResponses];

export type GetAdminWorkflowVersionData = {
    body?: never;
    path: {
        name: string;
        version: number;
    };
    query?: never;
    url: '/admin/api/v1/workflows/{name}/versions/{version}';
};

export type GetAdminWorkflowVersionErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Administrator role is required
     */
    403: unknown;
    /**
     * Workflow revision was not found
     */
    404: unknown;
    /**
     * Workflow store is unavailable
     */
    503: unknown;
};

export type GetAdminWorkflowVersionResponses = {
    200: WorkflowRevisionResponse;
};

export type GetAdminWorkflowVersionResponse = GetAdminWorkflowVersionResponses[keyof GetAdminWorkflowVersionResponses];

export type ListProviderConnectionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/app/api/v1/connections';
};

export type ListProviderConnectionsErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Connection broker is unavailable
     */
    503: unknown;
};

export type ListProviderConnectionsResponses = {
    200: ConnectionsCollectionResponse;
};

export type ListProviderConnectionsResponse = ListProviderConnectionsResponses[keyof ListProviderConnectionsResponses];

export type DisconnectProviderConnectionData = {
    body: DisconnectConnectionRequest;
    headers: {
        'X-Steward-CSRF': string;
    };
    path: {
        provider: string;
    };
    query?: never;
    url: '/app/api/v1/connections/{provider}/disconnect';
};

export type DisconnectProviderConnectionErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Origin, fetch metadata, or CSRF proof is invalid
     */
    403: unknown;
    /**
     * Provider is unavailable
     */
    404: unknown;
    409: ConnectionOperationErrorResponse;
    /**
     * Connection broker is unavailable
     */
    503: unknown;
};

export type DisconnectProviderConnectionError = DisconnectProviderConnectionErrors[keyof DisconnectProviderConnectionErrors];

export type DisconnectProviderConnectionResponses = {
    /**
     * Connection was disconnected
     */
    204: void;
};

export type DisconnectProviderConnectionResponse = DisconnectProviderConnectionResponses[keyof DisconnectProviderConnectionResponses];

export type StartProviderConnectionData = {
    body: BrowserMutationRequest;
    headers: {
        'X-Steward-CSRF': string;
    };
    path: {
        provider: string;
    };
    query?: never;
    url: '/app/api/v1/connections/{provider}/start';
};

export type StartProviderConnectionErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Origin, fetch metadata, or CSRF proof is invalid
     */
    403: unknown;
    /**
     * Provider is unavailable
     */
    404: unknown;
    /**
     * Connection broker is unavailable
     */
    503: unknown;
};

export type StartProviderConnectionResponses = {
    200: StartConnectionResponse;
};

export type StartProviderConnectionResponse = StartProviderConnectionResponses[keyof StartProviderConnectionResponses];

export type ListRequestsData = {
    body?: never;
    path?: never;
    query?: {
        status?: EnvelopeRequestStatus;
        cursor?: string;
    };
    url: '/app/api/v1/envelope-requests';
};

export type ListRequestsErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Envelope requests are unavailable
     */
    503: unknown;
};

export type ListRequestsResponses = {
    200: EnvelopeRequestsResponse;
};

export type ListRequestsResponse = ListRequestsResponses[keyof ListRequestsResponses];

export type CreateRequestData = {
    body: CreateEnvelopeRequestBody;
    headers: {
        'X-Steward-CSRF': string;
    };
    path?: never;
    query?: never;
    url: '/app/api/v1/envelope-requests';
};

export type CreateRequestErrors = {
    /**
     * Request is malformed
     */
    400: unknown;
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Origin, fetch metadata, or CSRF proof is invalid
     */
    403: unknown;
    /**
     * Template revision conflicts
     */
    409: unknown;
    /**
     * Requested envelope is invalid
     */
    422: unknown;
    /**
     * Envelope requests are unavailable
     */
    503: unknown;
};

export type CreateRequestResponses = {
    201: EnvelopeRequestResponse;
};

export type CreateRequestResponse = CreateRequestResponses[keyof CreateRequestResponses];

export type GetRequestData = {
    body?: never;
    path: {
        request_id: string;
    };
    query?: never;
    url: '/app/api/v1/envelope-requests/{request_id}';
};

export type GetRequestErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Envelope request was not found
     */
    404: unknown;
    /**
     * Envelope request is unavailable
     */
    503: unknown;
};

export type GetRequestResponses = {
    200: EnvelopeRequestResponse;
};

export type GetRequestResponse = GetRequestResponses[keyof GetRequestResponses];

export type RenderGithubActionsForEnvelopeData = {
    body: RenderGithubActionsWorkflowBody;
    headers: {
        'X-Steward-CSRF': string;
    };
    path: {
        request_id: string;
    };
    query?: never;
    url: '/app/api/v1/envelope-requests/{request_id}/github-actions-workflow';
};

export type RenderGithubActionsForEnvelopeErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Origin, fetch metadata, or CSRF proof is invalid
     */
    403: unknown;
    /**
     * Envelope request was not found
     */
    404: unknown;
    /**
     * Envelope request is not provisioned
     */
    409: unknown;
    /**
     * Workflow inputs are invalid
     */
    422: unknown;
    /**
     * Envelope request is unavailable
     */
    503: unknown;
};

export type RenderGithubActionsForEnvelopeResponses = {
    200: GithubActionsWorkflowResponse;
};

export type RenderGithubActionsForEnvelopeResponse = RenderGithubActionsForEnvelopeResponses[keyof RenderGithubActionsForEnvelopeResponses];

export type ListTemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/app/api/v1/envelope-templates';
};

export type ListTemplatesErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Envelope templates are unavailable
     */
    503: unknown;
};

export type ListTemplatesResponses = {
    200: EnvelopeTemplatesResponse;
};

export type ListTemplatesResponse = ListTemplatesResponses[keyof ListTemplatesResponses];

export type GetBrowserPreferencesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/app/api/v1/preferences';
};

export type GetBrowserPreferencesErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Preferences are unavailable
     */
    503: unknown;
};

export type GetBrowserPreferencesResponses = {
    200: BrowserPreferencesView;
};

export type GetBrowserPreferencesResponse = GetBrowserPreferencesResponses[keyof GetBrowserPreferencesResponses];

export type UpdateBrowserPreferencesData = {
    body: UpdateBrowserPreferences;
    headers: {
        'X-Steward-CSRF': string;
    };
    path?: never;
    query?: never;
    url: '/app/api/v1/preferences';
};

export type UpdateBrowserPreferencesErrors = {
    /**
     * At least one preference must be supplied
     */
    400: unknown;
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Origin, fetch metadata, or CSRF proof is invalid
     */
    403: unknown;
    /**
     * Preferences are unavailable
     */
    503: unknown;
};

export type UpdateBrowserPreferencesResponses = {
    200: BrowserPreferencesView;
};

export type UpdateBrowserPreferencesResponse = UpdateBrowserPreferencesResponses[keyof UpdateBrowserPreferencesResponses];

export type MyRunsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        cursor?: string;
        phase?: TaskPhase;
        workflow?: string;
        runtimeUid?: string;
        envelopeInstanceId?: string;
    };
    url: '/app/api/v1/runs';
};

export type MyRunsErrors = {
    /**
     * Run query is invalid
     */
    400: unknown;
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Run history is unavailable
     */
    503: unknown;
};

export type MyRunsResponses = {
    200: MyRunsResponse;
};

export type MyRunsResponse2 = MyRunsResponses[keyof MyRunsResponses];

export type MyRunData = {
    body?: never;
    path: {
        task_uid: string;
    };
    query?: never;
    url: '/app/api/v1/runs/{task_uid}';
};

export type MyRunErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Run was not found in the user's scope
     */
    404: unknown;
    /**
     * Run history is unavailable
     */
    503: unknown;
};

export type MyRunResponses = {
    200: BrowserRunResponse;
};

export type MyRunResponse = MyRunResponses[keyof MyRunResponses];

export type CancelMyRunData = {
    body?: never;
    headers: {
        'X-Steward-CSRF': string;
    };
    path: {
        task_uid: string;
    };
    query?: never;
    url: '/app/api/v1/runs/{task_uid}/cancel';
};

export type CancelMyRunErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Origin, fetch metadata, or CSRF proof is invalid
     */
    403: unknown;
    /**
     * Run was not found in the user's scope
     */
    404: unknown;
    /**
     * Run cancellation is unavailable
     */
    503: unknown;
};

export type CancelMyRunResponses = {
    200: BrowserRunResponse;
};

export type CancelMyRunResponse = CancelMyRunResponses[keyof CancelMyRunResponses];

export type MyRunExecutionLogData = {
    body?: never;
    path: {
        task_uid: string;
        /**
         * Exact execution stream: stdout or stderr
         */
        stream: string;
    };
    query?: {
        /**
         * Zero-based byte offset
         */
        after?: number;
    };
    url: '/app/api/v1/runs/{task_uid}/logs/{stream}';
};

export type MyRunExecutionLogErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Execution log was not found in the user's scope
     */
    404: unknown;
    /**
     * Run history is unavailable
     */
    503: unknown;
};

export type MyRunExecutionLogResponses = {
    200: BrowserExecutionLogResponse;
};

export type MyRunExecutionLogResponse = MyRunExecutionLogResponses[keyof MyRunExecutionLogResponses];

export type RerunMyRunData = {
    body: RerunRequest;
    headers: {
        'X-Steward-CSRF': string;
    };
    path: {
        task_uid: string;
    };
    query?: never;
    url: '/app/api/v1/runs/{task_uid}/rerun';
};

export type RerunMyRunErrors = {
    /**
     * Idempotency key is invalid
     */
    400: unknown;
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Origin, fetch metadata, or CSRF proof is invalid
     */
    403: unknown;
    /**
     * Run was not found in the user's scope
     */
    404: unknown;
    /**
     * The original envelope is no longer active or GitHub connection authorization is pending
     */
    409: unknown;
    /**
     * Run submission is unavailable
     */
    503: unknown;
};

export type RerunMyRunResponses = {
    /**
     * Idempotent replay
     */
    200: RerunResponse;
    201: RerunResponse;
    /**
     * GitHub accepted the rerun and Steward is awaiting the correlated Task
     */
    202: RerunPendingResponse;
};

export type RerunMyRunResponse = RerunMyRunResponses[keyof RerunMyRunResponses];

export type MyRunTimelineData = {
    body?: never;
    path: {
        task_uid: string;
    };
    query?: never;
    url: '/app/api/v1/runs/{task_uid}/timeline';
};

export type MyRunTimelineErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Run was not found in the user's scope
     */
    404: unknown;
    /**
     * Run history is unavailable
     */
    503: unknown;
};

export type MyRunTimelineResponses = {
    200: BrowserRunTimelineResponse;
};

export type MyRunTimelineResponse = MyRunTimelineResponses[keyof MyRunTimelineResponses];

export type ListPublishedWorkflowsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/app/api/v1/workflows';
};

export type ListPublishedWorkflowsErrors = {
    /**
     * Browser session is absent or invalid
     */
    401: unknown;
    /**
     * Workflow store is unavailable
     */
    503: unknown;
};

export type ListPublishedWorkflowsResponses = {
    200: PublishedWorkflowsResponse;
};

export type ListPublishedWorkflowsResponse = ListPublishedWorkflowsResponses[keyof ListPublishedWorkflowsResponses];

export type CreateRuntimeContractData = {
    body: CreateRuntimeRequest;
    path: {
        /**
         * AgentRuntime namespace
         */
        namespace: string;
    };
    query?: never;
    url: '/v1/namespaces/{namespace}/runtimes';
};

export type CreateRuntimeContractErrors = {
    /**
     * Authenticated principal does not own the runtime
     */
    403: unknown;
    /**
     * Kubernetes namespace does not exist
     */
    404: unknown;
    /**
     * AgentRuntime name already exists
     */
    409: unknown;
    /**
     * Manifest is invalid or cannot be bound to authority
     */
    422: unknown;
    /**
     * Kubernetes, authority store, or decision channel unavailable
     */
    503: unknown;
};

export type CreateRuntimeContractResponses = {
    /**
     * In-envelope runtime manifest admitted and created
     */
    201: unknown;
    /**
     * Over-envelope runtime manifest parked for approval
     */
    202: unknown;
};

export type BudgetIncreaseContractData = {
    body: BudgetIncrease;
    path: {
        /**
         * AgentRuntime namespace
         */
        namespace: string;
        /**
         * AgentRuntime name
         */
        name: string;
    };
    query?: never;
    url: '/v1/namespaces/{namespace}/runtimes/{name}/budget';
};

export type BudgetIncreaseContractErrors = {
    /**
     * Authenticated principal does not own the runtime
     */
    403: unknown;
    /**
     * Edit or composed manifest is invalid
     */
    422: unknown;
};

export type BudgetIncreaseContractResponses = {
    /**
     * Composed absolute manifest admitted and applied
     */
    200: unknown;
    /**
     * Composed absolute manifest rejected and parked
     */
    202: unknown;
};

export type TaskSubmissionContractData = {
    body: TaskCreateRequest;
    headers: {
        /**
         * Submitter-scoped upstream job identity
         */
        'Idempotency-Key': string;
    };
    path?: never;
    query?: never;
    url: '/v1/tasks';
};

export type TaskSubmissionContractErrors = {
    /**
     * Submission JSON is malformed
     */
    400: string;
    /**
     * Identity assertion is invalid
     */
    401: TaskErrorResponse;
    /**
     * Selected workflow does not exist
     */
    404: TaskErrorResponse;
    /**
     * Idempotency key conflicts with an existing Task
     */
    409: TaskErrorResponse;
    /**
     * Content-Type is not application/json
     */
    415: string;
    /**
     * Workflow, runtime version, User Envelope, or authority is invalid
     */
    422: TaskErrorResponse;
    /**
     * Identity, Kubernetes, persistence, or decision dependency unavailable
     */
    503: TaskErrorResponse;
};

export type TaskSubmissionContractError = TaskSubmissionContractErrors[keyof TaskSubmissionContractErrors];

export type TaskSubmissionContractResponses = {
    /**
     * An exact versioned-Workflow retry returns the existing Task under the frozen M1 contract; the request performs no runtime lifecycle effect
     */
    200: TaskStatusResponse;
    /**
     * A new direct-package or versioned Workflow Task is accepted for controller-owned runtime creation; runtimeUid is null until controller binding
     */
    202: TaskStatusResponse;
};

export type TaskSubmissionContractResponse = TaskSubmissionContractResponses[keyof TaskSubmissionContractResponses];

export type TaskDeleteContractData = {
    body?: never;
    path: {
        /**
         * Task lifecycle identity
         */
        taskUid: string;
    };
    query?: never;
    url: '/v1/tasks/{taskUid}';
};

export type TaskDeleteContractErrors = {
    /**
     * taskUid is not a UUID
     */
    400: string;
    /**
     * Identity assertion is invalid
     */
    401: TaskErrorResponse;
    /**
     * Task is not owned by the resolved submitter
     */
    404: TaskErrorResponse;
    /**
     * Identity or persistence dependency unavailable
     */
    503: TaskErrorResponse;
};

export type TaskDeleteContractError = TaskDeleteContractErrors[keyof TaskDeleteContractErrors];

export type TaskDeleteContractResponses = {
    /**
     * Cleanup requested durably; repeated requests are idempotent
     */
    202: TaskStatusResponse;
};

export type TaskDeleteContractResponse = TaskDeleteContractResponses[keyof TaskDeleteContractResponses];

export type TaskStatusContractData = {
    body?: never;
    path: {
        /**
         * Task lifecycle identity
         */
        taskUid: string;
    };
    query?: never;
    url: '/v1/tasks/{taskUid}';
};

export type TaskStatusContractErrors = {
    /**
     * taskUid is not a UUID
     */
    400: string;
    /**
     * Identity assertion is invalid
     */
    401: TaskErrorResponse;
    /**
     * Task is not owned by the resolved submitter
     */
    404: TaskErrorResponse;
    /**
     * Identity or persistence dependency unavailable
     */
    503: TaskErrorResponse;
};

export type TaskStatusContractError = TaskStatusContractErrors[keyof TaskStatusContractErrors];

export type TaskStatusContractResponses = {
    /**
     * Current durable Task phase and cleanup state
     */
    200: TaskStatusResponse;
};

export type TaskStatusContractResponse = TaskStatusContractResponses[keyof TaskStatusContractResponses];

export type TaskExecuteContractData = {
    body?: never;
    path: {
        /**
         * Task lifecycle identity
         */
        taskUid: string;
    };
    query?: never;
    url: '/v1/tasks/{taskUid}/execute';
};

export type TaskExecuteContractErrors = {
    /**
     * taskUid is not a UUID
     */
    400: string;
    /**
     * Identity assertion is invalid
     */
    401: TaskErrorResponse;
    /**
     * Task is not owned by the resolved submitter
     */
    404: TaskErrorResponse;
    /**
     * Inputs are absent, cleanup was requested, or the phase cannot execute
     */
    409: TaskErrorResponse;
    /**
     * Identity or persistence dependency unavailable
     */
    503: TaskErrorResponse;
};

export type TaskExecuteContractError = TaskExecuteContractErrors[keyof TaskExecuteContractErrors];

export type TaskExecuteContractResponses = {
    /**
     * Execution requested durably; repeated requests are idempotent
     */
    202: TaskStatusResponse;
};

export type TaskExecuteContractResponse = TaskExecuteContractResponses[keyof TaskExecuteContractResponses];

export type TaskInputsContractData = {
    /**
     * Opaque workspace-relative tar archive; maximum 64 MiB
     */
    body: TaskArchive;
    path: {
        /**
         * Task lifecycle identity
         */
        taskUid: string;
    };
    query?: never;
    url: '/v1/tasks/{taskUid}/inputs';
};

export type TaskInputsContractErrors = {
    /**
     * taskUid is not a UUID
     */
    400: string;
    /**
     * Identity assertion is invalid
     */
    401: TaskErrorResponse;
    /**
     * Task is not owned by the resolved submitter
     */
    404: TaskErrorResponse;
    /**
     * Task no longer accepts inputs or the retry body differs
     */
    409: TaskErrorResponse;
    /**
     * Input archive exceeds 64 MiB
     */
    413: TaskErrorResponse;
    /**
     * Content-Type is not application/x-tar
     */
    415: TaskErrorResponse;
    /**
     * Identity or persistence dependency unavailable
     */
    503: TaskErrorResponse;
};

export type TaskInputsContractError = TaskInputsContractErrors[keyof TaskInputsContractErrors];

export type TaskInputsContractResponses = {
    /**
     * Input archive staged durably; an identical retry is idempotent
     */
    204: void;
};

export type TaskInputsContractResponse = TaskInputsContractResponses[keyof TaskInputsContractResponses];

export type TaskOutputsContractData = {
    body?: never;
    path: {
        /**
         * Task lifecycle identity
         */
        taskUid: string;
    };
    query?: never;
    url: '/v1/tasks/{taskUid}/outputs';
};

export type TaskOutputsContractErrors = {
    /**
     * taskUid is not a UUID
     */
    400: string;
    /**
     * Identity assertion is invalid
     */
    401: TaskErrorResponse;
    /**
     * Task is not owned by the resolved submitter
     */
    404: TaskErrorResponse;
    /**
     * Task has not succeeded or output is not available
     */
    409: TaskErrorResponse;
    /**
     * Identity or persistence dependency unavailable
     */
    503: TaskErrorResponse;
};

export type TaskOutputsContractError = TaskOutputsContractErrors[keyof TaskOutputsContractErrors];

export type TaskOutputsContractResponses = {
    /**
     * Opaque workspace-relative output tar archive; maximum 64 MiB
     */
    200: TaskArchive;
};

export type TaskOutputsContractResponse = TaskOutputsContractResponses[keyof TaskOutputsContractResponses];
