use std::error::Error;
use std::fmt;

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::WorkflowReference;

pub const GITHUB_ACTIONS_RENDER_REQUEST_SCHEMA: &str = "steward/github-actions-render-request/v1";
pub const GITHUB_ACTIONS_RENDER_OUTPUT_SCHEMA: &str = "steward/github-actions-rendered-workflow/v1";
pub const VERSIONED_GITHUB_ACTIONS_RENDER_OUTPUT_SCHEMA: &str =
    "steward/github-actions-rendered-workflow/v2";
pub const GITHUB_FILE_READ_TEMPLATE: &str = "github-file-read/v1";

const REVIEWED_STEWARD_RUN_WORKFLOW_COMMIT: &str = "9c7487bd18d5e90b24b3e4b296bfdd232a3f4f5a";
const REVIEWED_STEWARD_RUN_ACTION_COMMIT: &str = "b26790e29ce9c243c6a7aa00450a2a1a98fbd250";
// Versioned Workflow runs are executed by the separately reviewed self-hosted
// reusable workflow. It preserves GitHub's `job_workflow_ref` OIDC claim while
// intentionally avoiding the ARC/ECR job container used by the legacy lane.
const VERSIONED_STEWARD_RUN_WORKFLOW_COMMIT: &str = "be04cf3acf43237327c26a06a36d784eadfdbe7a";
const VERSIONED_STEWARD_RUN_ACTION_COMMIT: &str = "19230cc59a6b1246224912961e35c7044b0808d3";
const REVIEWED_STEWARD_RUN_JOB_CONTAINER: &str = "663383948333.dkr.ecr.us-east-1.amazonaws.com/steward-run@sha256:27235891b596debb1d8bba5f7763e14a56ce4435e2fc82f3de80122b19ff8c61";

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct GithubActionsEnvelopeSelection {
    pub id: String,
    pub revision: u64,
    pub digest: String,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct StewardRunRelease {
    pub manifest_schema_version: u32,
    pub version: String,
    pub workflow_commit: String,
    pub action_commit: String,
    pub governed_job_container_image: String,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct GithubActionsTaskTemplate {
    pub id: String,
    pub repository: String,
    pub revision: String,
    pub path: String,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct GithubActionsRenderRequest {
    pub schema_version: String,
    pub envelope: GithubActionsEnvelopeSelection,
    pub release: StewardRunRelease,
    pub task_template: GithubActionsTaskTemplate,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GithubActionsRenderContext {
    pub current_envelope: GithubActionsEnvelopeSelection,
    pub reviewed_release: StewardRunRelease,
    /// Task template identifiers computed to fit within the authoritative envelope.
    pub allowed_task_templates: Vec<String>,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct GeneratedGithubActionsWorkflow {
    pub schema_version: String,
    pub content_type: String,
    pub sha256: String,
    pub yaml: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct VersionedGithubActionsWorkflowContext {
    pub envelope: GithubActionsEnvelopeSelection,
    pub workflow_name: String,
    pub workflow_version: i64,
    pub workflow_digest: String,
    pub reviewed_release: StewardRunRelease,
}

pub fn render_versioned_github_actions_workflow(
    workflow_reference: &str,
    context: &VersionedGithubActionsWorkflowContext,
) -> Result<GeneratedGithubActionsWorkflow, GithubActionsRenderError> {
    let reference = WorkflowReference::parse(workflow_reference)
        .map_err(|_| GithubActionsRenderError::InvalidRequest)?;
    if reference.name != context.workflow_name
        || reference.version != context.workflow_version
        || !valid_digest(&context.workflow_digest)
    {
        return Err(GithubActionsRenderError::InvalidRequest);
    }
    validate_envelope(&context.envelope)?;
    validate_release(&context.reviewed_release)?;
    if context.reviewed_release != reviewed_steward_run_release_v2() {
        return Err(GithubActionsRenderError::UnreviewedRelease);
    }
    let release = &context.reviewed_release;
    let yaml = [
        "# Generated by Steward. Review before committing to a repository.".to_owned(),
        format!("# generator: {VERSIONED_GITHUB_ACTIONS_RENDER_OUTPUT_SCHEMA}"),
        format!("# envelope-id: {}", context.envelope.id),
        format!("# envelope-revision: {}", context.envelope.revision),
        format!("# envelope-digest: {}", context.envelope.digest),
        format!("# workflow: {workflow_reference}"),
        format!("# workflow-digest: {}", context.workflow_digest),
        format!("# steward-run-version: {}", release.version),
        format!("# steward-run-workflow-commit: {}", release.workflow_commit),
        String::new(),
        "name: Steward governed repository review".to_owned(),
        String::new(),
        "'on':".to_owned(),
        "  workflow_dispatch:".to_owned(),
        String::new(),
        "permissions: {}".to_owned(),
        String::new(),
        "jobs:".to_owned(),
        "  prepare:".to_owned(),
        "    name: Snapshot triggered repository state".to_owned(),
        "    runs-on: ${{ vars.STEWARD_RUNNER_LABEL }}".to_owned(),
        "    timeout-minutes: 5".to_owned(),
        "    permissions:".to_owned(),
        "      contents: read".to_owned(),
        "    steps:".to_owned(),
        "      - name: Check out triggered revision".to_owned(),
        "        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2"
            .to_owned(),
        "        with:".to_owned(),
        "          persist-credentials: false".to_owned(),
        "      - name: Upload repository snapshot".to_owned(),
        "        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2"
            .to_owned(),
        "        with:".to_owned(),
        "          name: steward-workflow-input".to_owned(),
        "          path: .".to_owned(),
        "          if-no-files-found: error".to_owned(),
        "          include-hidden-files: false".to_owned(),
        "          retention-days: 1".to_owned(),
        String::new(),
        "  governed:".to_owned(),
        "    name: Run governed Workflow".to_owned(),
        "    needs: prepare".to_owned(),
        "    permissions:".to_owned(),
        "      contents: read".to_owned(),
        "      id-token: write".to_owned(),
        format!(
            "    uses: apelogic-ai/steward-run/.github/workflows/steward-task-self-hosted.yml@{}",
            release.workflow_commit
        ),
        "    with:".to_owned(),
        "      runner-label: ${{ vars.STEWARD_RUNNER_LABEL }}".to_owned(),
        format!("      workflow: {workflow_reference}"),
        "      input-artifact: steward-workflow-input".to_owned(),
        "      output-artifact: steward-workflow-output".to_owned(),
        "      steward-api-url: ${{ vars.STEWARD_API_URL }}".to_owned(),
        "      identity-exchange-url: ${{ vars.IDENTITY_EXCHANGE_URL }}".to_owned(),
        "      oidc-audience: ${{ vars.IDENTITY_EXCHANGE_AUDIENCE }}".to_owned(),
        "      steward-ca-certificate-file: ${{ vars.STEWARD_CA_CERTIFICATE_FILE }}".to_owned(),
        String::new(),
        "  verify:".to_owned(),
        "    name: Verify governed result".to_owned(),
        "    needs: governed".to_owned(),
        "    runs-on: ${{ vars.STEWARD_RUNNER_LABEL }}".to_owned(),
        "    timeout-minutes: 5".to_owned(),
        "    permissions:".to_owned(),
        "      contents: read".to_owned(),
        "    steps:".to_owned(),
        "      - name: Download governed output".to_owned(),
        "        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0"
            .to_owned(),
        "        with:".to_owned(),
        "          name: steward-workflow-output".to_owned(),
        "          path: output".to_owned(),
        "      - name: Require a non-empty result".to_owned(),
        "        shell: bash".to_owned(),
        "        run: test -n \"$(find output -type f -size +0c -print -quit)\"".to_owned(),
    ]
    .join("\n")
        + "\n";
    let sha256 = format!("sha256:{:x}", Sha256::digest(yaml.as_bytes()));
    Ok(GeneratedGithubActionsWorkflow {
        schema_version: VERSIONED_GITHUB_ACTIONS_RENDER_OUTPUT_SCHEMA.to_owned(),
        content_type: "application/yaml".to_owned(),
        sha256,
        yaml,
    })
}

/// The reviewed, immutable steward-run release used by the v1 generator contract.
/// Any release change must be an explicit renderer-contract update with a new golden fixture.
pub fn reviewed_steward_run_release_v1() -> StewardRunRelease {
    StewardRunRelease {
        manifest_schema_version: 4,
        version: "0.3.7".to_owned(),
        workflow_commit: REVIEWED_STEWARD_RUN_WORKFLOW_COMMIT.to_owned(),
        action_commit: REVIEWED_STEWARD_RUN_ACTION_COMMIT.to_owned(),
        governed_job_container_image: REVIEWED_STEWARD_RUN_JOB_CONTAINER.to_owned(),
    }
}

/// The reviewed immutable steward-run handoff for versioned Steward Workflows.
/// Legacy static smoke workflows remain pinned to [`reviewed_steward_run_release_v1`].
pub fn reviewed_steward_run_release_v2() -> StewardRunRelease {
    StewardRunRelease {
        manifest_schema_version: 4,
        version: "0.4.0".to_owned(),
        workflow_commit: VERSIONED_STEWARD_RUN_WORKFLOW_COMMIT.to_owned(),
        action_commit: VERSIONED_STEWARD_RUN_ACTION_COMMIT.to_owned(),
        governed_job_container_image: REVIEWED_STEWARD_RUN_JOB_CONTAINER.to_owned(),
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum GithubActionsRenderError {
    InvalidRequest,
    UnsupportedSchema,
    StaleEnvelope,
    UnreviewedRelease,
    UnsupportedTemplate,
    UnsupportedEnvelopeAuthority,
    InvalidRepository,
    InvalidRevision,
    InvalidPath,
    SecretLikeInput,
    InvalidGeneratedWorkflow,
}

impl fmt::Display for GithubActionsRenderError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::InvalidRequest => "GitHub Actions render request is invalid",
            Self::UnsupportedSchema => "GitHub Actions render request schema is unsupported",
            Self::StaleEnvelope => "selected Steward envelope is stale",
            Self::UnreviewedRelease => "steward-run release is not the reviewed release",
            Self::UnsupportedTemplate => "GitHub Actions task template is unsupported",
            Self::UnsupportedEnvelopeAuthority => {
                "GitHub Actions task template is outside the selected envelope"
            }
            Self::InvalidRepository => "GitHub repository is invalid",
            Self::InvalidRevision => "GitHub revision is invalid",
            Self::InvalidPath => "GitHub path is invalid",
            Self::SecretLikeInput => "GitHub Actions request contains secret-like input",
            Self::InvalidGeneratedWorkflow => "generated GitHub Actions workflow is invalid",
        })
    }
}

impl Error for GithubActionsRenderError {}

pub fn parse_github_actions_render_request(
    value: &str,
) -> Result<GithubActionsRenderRequest, GithubActionsRenderError> {
    serde_json::from_str(value).map_err(|_| GithubActionsRenderError::InvalidRequest)
}

pub fn render_github_actions_workflow(
    request: &GithubActionsRenderRequest,
    context: &GithubActionsRenderContext,
) -> Result<GeneratedGithubActionsWorkflow, GithubActionsRenderError> {
    validate_request(request, context)?;
    let release = &request.release;
    let template = &request.task_template;
    let envelope = &request.envelope;
    let yaml = [
        "# Generated by Steward. Review before committing to a repository.".to_owned(),
        format!("# generator: {GITHUB_ACTIONS_RENDER_OUTPUT_SCHEMA}"),
        format!("# envelope-id: {}", envelope.id),
        format!("# envelope-revision: {}", envelope.revision),
        format!("# envelope-digest: {}", envelope.digest),
        format!("# task-template: {}", template.id),
        format!(
            "# steward-run-release-manifest-schema: {}",
            release.manifest_schema_version
        ),
        format!("# steward-run-version: {}", release.version),
        format!("# steward-run-workflow-commit: {}", release.workflow_commit),
        format!("# steward-run-action-commit: {}", release.action_commit),
        format!(
            "# governed-job-container: {}",
            release.governed_job_container_image
        ),
        String::new(),
        "name: Steward governed GitHub file read".to_owned(),
        String::new(),
        "'on':".to_owned(),
        "  workflow_dispatch:".to_owned(),
        String::new(),
        "permissions: {}".to_owned(),
        String::new(),
        "jobs:".to_owned(),
        "  seed:".to_owned(),
        "    name: Create immutable request".to_owned(),
        "    runs-on: ${{ vars.STEWARD_RUNNER_LABEL }}".to_owned(),
        "    timeout-minutes: 5".to_owned(),
        "    container:".to_owned(),
        format!("      image: {}", release.governed_job_container_image),
        "    permissions:".to_owned(),
        "      contents: read".to_owned(),
        "    steps:".to_owned(),
        "      - name: Create immutable GitHub file request".to_owned(),
        "        shell: bash".to_owned(),
        "        env:".to_owned(),
        format!("          TARGET_REPOSITORY: {}", yaml_string(&template.repository)),
        format!("          TARGET_REVISION: {}", yaml_string(&template.revision)),
        format!("          TARGET_PATH: {}", yaml_string(&template.path)),
        "        run: |".to_owned(),
        "          set -euo pipefail".to_owned(),
        "          mkdir -p in".to_owned(),
        "          node <<'NODE'".to_owned(),
        "          const fs = require('node:fs');".to_owned(),
        "          const request = {".to_owned(),
        "            repository: process.env.TARGET_REPOSITORY,".to_owned(),
        "            revision: process.env.TARGET_REVISION,".to_owned(),
        "            path: process.env.TARGET_PATH,".to_owned(),
        "          };".to_owned(),
        "          fs.writeFileSync('in/request.json', `${JSON.stringify(request)}\\n`, { mode: 0o600 });"
            .to_owned(),
        "          NODE".to_owned(),
        "      - name: Upload immutable request".to_owned(),
        "        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2"
            .to_owned(),
        "        with:".to_owned(),
        "          name: steward-github-file-read-input".to_owned(),
        "          path: in/request.json".to_owned(),
        "          if-no-files-found: error".to_owned(),
        "          retention-days: 1".to_owned(),
        String::new(),
        "  governed:".to_owned(),
        "    name: Run governed GitHub file read".to_owned(),
        "    needs: seed".to_owned(),
        "    permissions:".to_owned(),
        "      contents: read".to_owned(),
        "      id-token: write".to_owned(),
        format!(
            "    uses: apelogic-ai/steward-run/.github/workflows/steward-task.yml@{}",
            release.workflow_commit
        ),
        "    with:".to_owned(),
        "      runner-label: ${{ vars.STEWARD_RUNNER_LABEL }}".to_owned(),
        "      workflow: github-file-agent-smoke".to_owned(),
        "      input-artifact: steward-github-file-read-input".to_owned(),
        "      output-artifact: steward-github-file-read-output".to_owned(),
        "      steward-api-url: ${{ vars.STEWARD_API_URL }}".to_owned(),
        "      identity-exchange-url: ${{ vars.IDENTITY_EXCHANGE_URL }}".to_owned(),
        "      steward-ca-certificate-file: ${{ vars.STEWARD_CA_CERTIFICATE_FILE }}".to_owned(),
        "      coding-agent-runtime: base".to_owned(),
        String::new(),
        "  verify:".to_owned(),
        "    name: Verify governed result".to_owned(),
        "    needs: governed".to_owned(),
        "    runs-on: ${{ vars.STEWARD_RUNNER_LABEL }}".to_owned(),
        "    timeout-minutes: 5".to_owned(),
        "    container:".to_owned(),
        format!("      image: {}", release.governed_job_container_image),
        "    permissions:".to_owned(),
        "      contents: read".to_owned(),
        "    steps:".to_owned(),
        "      - name: Download governed output".to_owned(),
        "        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0"
            .to_owned(),
        "        with:".to_owned(),
        "          name: steward-github-file-read-output".to_owned(),
        "          path: output".to_owned(),
        "      - name: Require successful finalized Task and non-empty output".to_owned(),
        "        shell: bash".to_owned(),
        "        env:".to_owned(),
        "          STEWARD_STATUS: ${{ needs.governed.outputs.status }}".to_owned(),
        "          STEWARD_TASK_UID: ${{ needs.governed.outputs.task-uid }}".to_owned(),
        "          STEWARD_RUNTIME_UID: ${{ needs.governed.outputs.runtime-uid }}".to_owned(),
        "        run: |".to_owned(),
        "          set -euo pipefail".to_owned(),
        "          test \"$STEWARD_STATUS\" = succeeded".to_owned(),
        "          test -n \"$STEWARD_TASK_UID\"".to_owned(),
        "          test -n \"$STEWARD_RUNTIME_UID\"".to_owned(),
        "          test -n \"$(find output -type f -size +0c -print -quit)\"".to_owned(),
    ]
    .join("\n")
        + "\n";
    let sha256 = format!("sha256:{:x}", Sha256::digest(yaml.as_bytes()));
    Ok(GeneratedGithubActionsWorkflow {
        schema_version: GITHUB_ACTIONS_RENDER_OUTPUT_SCHEMA.to_owned(),
        content_type: "application/yaml".to_owned(),
        sha256,
        yaml,
    })
}

pub fn validate_generated_github_actions_yaml(
    value: &str,
    request: &GithubActionsRenderRequest,
    context: &GithubActionsRenderContext,
) -> Result<(), GithubActionsRenderError> {
    if value.len() > 32 * 1024 {
        return Err(GithubActionsRenderError::InvalidGeneratedWorkflow);
    }
    let options = serde_saphyr::options! {
        budget: serde_saphyr::budget! {
            max_events: 1_000,
            max_aliases: 0,
            max_anchors: 0,
            max_depth: 16,
            max_inclusion_depth: 0,
            max_documents: 1,
            max_nodes: 500,
            max_total_scalar_bytes: 24 * 1024,
            max_total_comment_bytes: 4 * 1024,
            max_merge_keys: 0,
        },
        duplicate_keys: serde_saphyr::DuplicateKeyPolicy::Error,
        merge_keys: serde_saphyr::MergeKeyPolicy::Error,
        alias_limits: serde_saphyr::alias_limits! {
            max_total_replayed_events: 0,
            max_replay_stack_depth: 0,
            max_alias_expansions_per_anchor: 0,
        },
        strict_booleans: true,
        require_indent: serde_saphyr::RequireIndent::Even,
    };
    serde_saphyr::from_str_with_options::<serde_json::Value>(value, options)
        .map_err(|_| GithubActionsRenderError::InvalidGeneratedWorkflow)?;
    let expected = render_github_actions_workflow(request, context)?;
    if value != expected.yaml {
        return Err(GithubActionsRenderError::InvalidGeneratedWorkflow);
    }
    Ok(())
}

fn validate_request(
    request: &GithubActionsRenderRequest,
    context: &GithubActionsRenderContext,
) -> Result<(), GithubActionsRenderError> {
    if request.schema_version != GITHUB_ACTIONS_RENDER_REQUEST_SCHEMA {
        return Err(GithubActionsRenderError::UnsupportedSchema);
    }
    validate_envelope(&context.current_envelope)?;
    validate_release(&context.reviewed_release)?;
    if request.envelope != context.current_envelope {
        return Err(GithubActionsRenderError::StaleEnvelope);
    }
    if request.release != context.reviewed_release {
        return Err(GithubActionsRenderError::UnreviewedRelease);
    }
    if request.task_template.id != GITHUB_FILE_READ_TEMPLATE {
        return Err(GithubActionsRenderError::UnsupportedTemplate);
    }
    if !context
        .allowed_task_templates
        .iter()
        .any(|template| template == &request.task_template.id)
    {
        return Err(GithubActionsRenderError::UnsupportedEnvelopeAuthority);
    }
    let template = &request.task_template;
    if [
        template.repository.as_str(),
        template.path.as_str(),
        request.envelope.id.as_str(),
    ]
    .iter()
    .any(|value| secret_like(value))
    {
        return Err(GithubActionsRenderError::SecretLikeInput);
    }
    if !valid_repository(&template.repository) {
        return Err(GithubActionsRenderError::InvalidRepository);
    }
    if !valid_full_sha(&template.revision) {
        return Err(GithubActionsRenderError::InvalidRevision);
    }
    if !valid_path(&template.path) {
        return Err(GithubActionsRenderError::InvalidPath);
    }
    Ok(())
}

fn validate_envelope(
    envelope: &GithubActionsEnvelopeSelection,
) -> Result<(), GithubActionsRenderError> {
    if envelope.revision == 0
        || envelope.id.is_empty()
        || envelope.id.len() > 63
        || !envelope.id.chars().all(|character| {
            character.is_ascii_lowercase()
                || character.is_ascii_digit()
                || matches!(character, '-' | '_' | '.')
        })
        || !valid_digest(&envelope.digest)
    {
        return Err(GithubActionsRenderError::InvalidRequest);
    }
    Ok(())
}

fn validate_release(release: &StewardRunRelease) -> Result<(), GithubActionsRenderError> {
    if release.manifest_schema_version != 4
        || !valid_semver(&release.version)
        || !valid_full_sha(&release.workflow_commit)
        || !valid_full_sha(&release.action_commit)
        || !valid_immutable_image(&release.governed_job_container_image)
    {
        return Err(GithubActionsRenderError::UnreviewedRelease);
    }
    Ok(())
}

fn valid_semver(value: &str) -> bool {
    let parts: Vec<&str> = value.split('.').collect();
    parts.len() == 3
        && parts.iter().all(|part| {
            !part.is_empty()
                && part.chars().all(|character| character.is_ascii_digit())
                && (part == &"0" || !part.starts_with('0'))
        })
}

fn valid_full_sha(value: &str) -> bool {
    value.len() == 40
        && value
            .chars()
            .all(|character| character.is_ascii_digit() || ('a'..='f').contains(&character))
}

fn valid_digest(value: &str) -> bool {
    value.strip_prefix("sha256:").is_some_and(|digest| {
        digest.len() == 64
            && digest
                .chars()
                .all(|character| character.is_ascii_digit() || ('a'..='f').contains(&character))
    })
}

fn valid_immutable_image(value: &str) -> bool {
    let Some((repository, digest)) = value.split_once('@') else {
        return false;
    };
    !repository.is_empty()
        && !repository.contains(char::is_whitespace)
        && !repository.contains(':')
        && valid_digest(digest)
}

fn valid_repository(value: &str) -> bool {
    if value.is_empty() || value.len() > 200 {
        return false;
    }
    let parts: Vec<&str> = value.split('/').collect();
    parts.len() == 2 && parts.iter().all(|part| valid_repository_part(part))
}

fn valid_repository_part(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= 100
        && value != "."
        && value != ".."
        && value.chars().all(|character| {
            character.is_ascii_alphanumeric() || matches!(character, '-' | '_' | '.')
        })
}

fn valid_path(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= 240
        && !value.starts_with('/')
        && !value.contains('\\')
        && value.split('/').all(|part| {
            !part.is_empty()
                && part != "."
                && part != ".."
                && part.chars().all(|character| {
                    character.is_ascii_alphanumeric() || matches!(character, '-' | '_' | '.')
                })
        })
}

fn secret_like(value: &str) -> bool {
    let lowercase = value.to_ascii_lowercase();
    value.chars().any(char::is_control)
        || [
            "secret",
            "token",
            "password",
            "credential",
            "private-key",
            "private_key",
            "${{",
            "}}",
            "akia",
        ]
        .iter()
        .any(|marker| lowercase.contains(marker))
}

fn yaml_string(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

#[cfg(test)]
mod tests {
    use super::{
        GITHUB_ACTIONS_RENDER_REQUEST_SCHEMA, GITHUB_FILE_READ_TEMPLATE,
        GithubActionsEnvelopeSelection, GithubActionsRenderContext, GithubActionsRenderError,
        GithubActionsRenderRequest, GithubActionsTaskTemplate, StewardRunRelease,
        VersionedGithubActionsWorkflowContext, parse_github_actions_render_request,
        render_github_actions_workflow, render_versioned_github_actions_workflow,
        validate_generated_github_actions_yaml,
    };

    const WORKFLOW_COMMIT: &str = "9c7487bd18d5e90b24b3e4b296bfdd232a3f4f5a";
    const ACTION_COMMIT: &str = "b26790e29ce9c243c6a7aa00450a2a1a98fbd250";
    const VERSIONED_WORKFLOW_COMMIT: &str = "be04cf3acf43237327c26a06a36d784eadfdbe7a";
    const VERSIONED_ACTION_COMMIT: &str = "19230cc59a6b1246224912961e35c7044b0808d3";
    const JOB_CONTAINER: &str = "663383948333.dkr.ecr.us-east-1.amazonaws.com/steward-run@sha256:27235891b596debb1d8bba5f7763e14a56ce4435e2fc82f3de80122b19ff8c61";

    fn envelope() -> GithubActionsEnvelopeSelection {
        GithubActionsEnvelopeSelection {
            id: "engineer".to_owned(),
            revision: 7,
            digest: "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
                .to_owned(),
        }
    }

    #[test]
    fn versioned_generator_uses_native_trigger_and_exact_workflow_without_source_overrides()
    -> Result<(), GithubActionsRenderError> {
        let generated = render_versioned_github_actions_workflow(
            "repository-review@1",
            &VersionedGithubActionsWorkflowContext {
                envelope: envelope(),
                workflow_name: "repository-review".to_owned(),
                workflow_version: 1,
                workflow_digest:
                    "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
                        .to_owned(),
                reviewed_release: versioned_release(),
            },
        )?;
        assert!(generated.yaml.contains("  workflow_dispatch:"));
        assert!(
            generated
                .yaml
                .contains("      workflow: repository-review@1")
        );
        assert!(
            generated.yaml.contains(
                "uses: apelogic-ai/steward-run/.github/workflows/steward-task-self-hosted.yml@be04cf3acf43237327c26a06a36d784eadfdbe7a"
            ),
            "versioned runs must preserve reusable-workflow OIDC provenance without inheriting the ARC ECR container"
        );
        assert!(!generated.yaml.contains("steward-task.yml@"));
        assert!(!generated.yaml.contains("coding-agent-runtime"));
        assert!(!generated.yaml.contains("TARGET_REVISION"));
        assert!(!generated.yaml.contains("TARGET_PATH"));
        assert!(!generated.yaml.contains("full commit SHA"));
        assert!(!generated.yaml.contains("src/lib.rs"));
        assert!(
            generated
                .yaml
                .contains("      oidc-audience: ${{ vars.IDENTITY_EXCHANGE_AUDIENCE }}"),
            "the reusable workflow must receive the exact local Identity audience"
        );
        assert!(
            generated
                .yaml
                .contains("          persist-credentials: false"),
            "the checkout token must never be written into the repository snapshot"
        );
        assert!(
            generated
                .yaml
                .contains("          include-hidden-files: false"),
            "the governed input must exclude dotfiles, which can contain credentials"
        );
        Ok(())
    }

    fn release() -> StewardRunRelease {
        StewardRunRelease {
            manifest_schema_version: 4,
            version: "0.3.7".to_owned(),
            workflow_commit: WORKFLOW_COMMIT.to_owned(),
            action_commit: ACTION_COMMIT.to_owned(),
            governed_job_container_image: JOB_CONTAINER.to_owned(),
        }
    }

    fn versioned_release() -> StewardRunRelease {
        StewardRunRelease {
            manifest_schema_version: 4,
            version: "0.4.0".to_owned(),
            workflow_commit: VERSIONED_WORKFLOW_COMMIT.to_owned(),
            action_commit: VERSIONED_ACTION_COMMIT.to_owned(),
            governed_job_container_image: JOB_CONTAINER.to_owned(),
        }
    }

    fn request() -> GithubActionsRenderRequest {
        GithubActionsRenderRequest {
            schema_version: GITHUB_ACTIONS_RENDER_REQUEST_SCHEMA.to_owned(),
            envelope: envelope(),
            release: release(),
            task_template: GithubActionsTaskTemplate {
                id: GITHUB_FILE_READ_TEMPLATE.to_owned(),
                repository: "example-org/example-repository".to_owned(),
                revision: "0123456789abcdef0123456789abcdef01234567".to_owned(),
                path: "README.md".to_owned(),
            },
        }
    }

    fn context() -> GithubActionsRenderContext {
        GithubActionsRenderContext {
            current_envelope: envelope(),
            reviewed_release: release(),
            allowed_task_templates: vec![GITHUB_FILE_READ_TEMPLATE.to_owned()],
        }
    }

    #[test]
    fn strict_request_parser_rejects_unknown_and_duplicate_fields() -> Result<(), String> {
        let valid = serde_json::to_string(&request())
            .map_err(|error| format!("fixture failed to serialize: {error}"))?;
        assert_eq!(
            parse_github_actions_render_request(&valid),
            Ok(request()),
            "the versioned request must parse before any rendering"
        );

        let unknown = valid.replacen(
            r#"{"schemaVersion":"#,
            r#"{"permissions":{"contents":"write"},"schemaVersion":"#,
            1,
        );
        assert_eq!(
            parse_github_actions_render_request(&unknown),
            Err(GithubActionsRenderError::InvalidRequest),
            "unknown authority-bearing fields must fail closed"
        );

        let duplicate = valid.replacen(
            r#"{"schemaVersion":"#,
            r#"{"schemaVersion":"steward/github-actions-render-request/v1","schemaVersion":"#,
            1,
        );
        assert_eq!(
            parse_github_actions_render_request(&duplicate),
            Err(GithubActionsRenderError::InvalidRequest),
            "duplicate JSON members must never choose a winner"
        );

        let duplicate_nested_member = valid.replacen(
            r#""repository":"example-org/example-repository""#,
            r#""repository":"example-org/first","repository":"example-org/example-repository""#,
            1,
        );
        assert_eq!(
            parse_github_actions_render_request(&duplicate_nested_member),
            Err(GithubActionsRenderError::InvalidRequest),
            "duplicate members in nested authority-bearing objects must fail closed"
        );
        Ok(())
    }

    #[test]
    fn rendering_rejects_stale_envelopes_and_unreviewed_or_mutable_release_coordinates() {
        let mut stale = request();
        stale.envelope.revision = 6;
        assert_eq!(
            render_github_actions_workflow(&stale, &context()),
            Err(GithubActionsRenderError::StaleEnvelope)
        );

        let mut mutable = request();
        mutable.release.workflow_commit = "main".to_owned();
        assert_eq!(
            render_github_actions_workflow(&mutable, &context()),
            Err(GithubActionsRenderError::UnreviewedRelease)
        );

        let mut different_container = request();
        different_container.release.governed_job_container_image =
            "example.invalid/steward-run:latest".to_owned();
        assert_eq!(
            render_github_actions_workflow(&different_container, &context()),
            Err(GithubActionsRenderError::UnreviewedRelease)
        );
    }

    #[test]
    fn rendering_rejects_arbitrary_secret_like_and_ambiguous_template_inputs() {
        let mut unsupported = request();
        unsupported.task_template.id = "arbitrary-shell/v1".to_owned();
        assert_eq!(
            render_github_actions_workflow(&unsupported, &context()),
            Err(GithubActionsRenderError::UnsupportedTemplate)
        );

        let mut secret_like = request();
        secret_like.task_template.path = "credentials/access-token.txt".to_owned();
        assert_eq!(
            render_github_actions_workflow(&secret_like, &context()),
            Err(GithubActionsRenderError::SecretLikeInput)
        );

        let mut traversal = request();
        traversal.task_template.path = "docs/../README.md".to_owned();
        assert_eq!(
            render_github_actions_workflow(&traversal, &context()),
            Err(GithubActionsRenderError::InvalidPath)
        );

        let mut tag = request();
        tag.task_template.revision = "v1.2.3".to_owned();
        assert_eq!(
            render_github_actions_workflow(&tag, &context()),
            Err(GithubActionsRenderError::InvalidRevision)
        );
    }

    #[test]
    fn reviewed_inputs_render_byte_identical_minimal_governed_workflow() -> Result<(), String> {
        let first = render_github_actions_workflow(&request(), &context())
            .map_err(|error| format!("reviewed request failed to render: {error}"))?;
        let second = render_github_actions_workflow(&request(), &context())
            .map_err(|error| format!("same reviewed request failed to render again: {error}"))?;
        assert_eq!(first, second, "rendering must be byte deterministic");
        assert_eq!(
            first.yaml,
            include_str!("../../../docs/examples/github-file-read-v1.yaml"),
            "the reviewed renderer contract must change only through an explicit golden update"
        );
        assert!(first.yaml.ends_with('\n'));
        assert!(first.yaml.contains("envelope-id: engineer"));
        assert!(first.yaml.contains("envelope-revision: 7"));
        assert!(first.yaml.contains(WORKFLOW_COMMIT));
        assert!(first.yaml.contains(ACTION_COMMIT));
        assert!(first.yaml.contains(JOB_CONTAINER));
        assert_eq!(
            first.yaml.matches(WORKFLOW_COMMIT).count(),
            2,
            "the reusable workflow pin must appear once as provenance and once as the executable reference"
        );
        assert_eq!(
            first.yaml.matches(ACTION_COMMIT).count(),
            1,
            "the signed release's nested action pin must be preserved as provenance"
        );
        assert_eq!(
            first.yaml.matches(JOB_CONTAINER).count(),
            3,
            "the reviewed job container must bind provenance and both caller-owned jobs"
        );
        assert!(first.yaml.contains(
            "uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2"
        ));
        assert!(first.yaml.contains(
            "uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0"
        ));
        assert_eq!(
            first
                .yaml
                .matches("runs-on: ${{ vars.STEWARD_RUNNER_LABEL }}")
                .count(),
            2,
            "both caller-owned jobs must retain ARC runner enforcement"
        );
        assert!(
            first
                .yaml
                .contains("runner-label: ${{ vars.STEWARD_RUNNER_LABEL }}")
        );
        assert!(
            first
                .yaml
                .contains("steward-ca-certificate-file: ${{ vars.STEWARD_CA_CERTIFICATE_FILE }}")
        );
        assert!(
            first
                .yaml
                .contains("input-artifact: steward-github-file-read-input")
        );
        assert!(
            first
                .yaml
                .contains("output-artifact: steward-github-file-read-output")
        );
        assert!(
            first
                .yaml
                .contains("STEWARD_STATUS: ${{ needs.governed.outputs.status }}")
        );
        assert!(
            first
                .yaml
                .contains("    permissions:\n      contents: read\n      id-token: write")
        );
        assert!(!first.yaml.contains("contents: write"));
        assert!(!first.yaml.contains("pull-requests: write"));
        assert!(!first.yaml.contains("secrets:"));
        assert!(!first.yaml.contains("actions/checkout@"));
        assert!(!first.yaml.contains("curl "));
        assert!(!first.yaml.contains("gh "));
        assert!(!first.yaml.contains("@main"));
        assert!(!first.yaml.contains(":latest"));
        assert_eq!(
            first.sha256,
            "sha256:cd25dd0b56c699526b78165eff513f9196c940df196b91a686881922f177c2e8"
        );
        Ok(())
    }

    #[test]
    fn strict_yaml_validation_rejects_duplicates_aliases_merge_keys_and_drift() -> Result<(), String>
    {
        let request = request();
        let context = context();
        let rendered = render_github_actions_workflow(&request, &context)
            .map_err(|error| format!("reviewed request failed to render: {error}"))?;
        assert_eq!(
            validate_generated_github_actions_yaml(&rendered.yaml, &request, &context),
            Ok(()),
            "the canonical generated workflow must pass the strict parser"
        );

        let duplicate = rendered.yaml.replacen(
            "name: Steward governed GitHub file read",
            "name: first\nname: second",
            1,
        );
        assert_eq!(
            validate_generated_github_actions_yaml(&duplicate, &request, &context),
            Err(GithubActionsRenderError::InvalidGeneratedWorkflow)
        );

        let alias = rendered.yaml.replacen(
            "permissions: {}",
            "permissions: &permissions {}\nalias: *permissions",
            1,
        );
        assert_eq!(
            validate_generated_github_actions_yaml(&alias, &request, &context),
            Err(GithubActionsRenderError::InvalidGeneratedWorkflow)
        );

        let merge = rendered.yaml.replacen(
            "permissions: {}",
            "permissions: {}\n<<: {permissions: {}}",
            1,
        );
        assert_eq!(
            validate_generated_github_actions_yaml(&merge, &request, &context),
            Err(GithubActionsRenderError::InvalidGeneratedWorkflow)
        );

        let ambiguous = rendered.yaml.replacen("'on':", "on:", 1).replacen(
            "workflow_dispatch:",
            "workflow_dispatch: yes",
            1,
        );
        assert_eq!(
            validate_generated_github_actions_yaml(&ambiguous, &request, &context),
            Err(GithubActionsRenderError::InvalidGeneratedWorkflow)
        );
        Ok(())
    }

    #[test]
    fn rendering_rejects_invalid_context_and_authority_outside_the_envelope() {
        let mut unreviewed_context = context();
        unreviewed_context.reviewed_release.workflow_commit = "main".to_owned();
        assert_eq!(
            render_github_actions_workflow(&request(), &unreviewed_context),
            Err(GithubActionsRenderError::UnreviewedRelease),
            "a mutable server-side release configuration must not bless a request"
        );

        let mut outside_envelope = context();
        outside_envelope.allowed_task_templates.clear();
        assert_eq!(
            render_github_actions_workflow(&request(), &outside_envelope),
            Err(GithubActionsRenderError::UnsupportedEnvelopeAuthority),
            "a supported template still requires an authoritative envelope fit decision"
        );

        let mut invalid_repository = request();
        invalid_repository.task_template.repository = "example-org/repository/extra".to_owned();
        assert_eq!(
            render_github_actions_workflow(&invalid_repository, &context()),
            Err(GithubActionsRenderError::InvalidRepository)
        );
    }
}
